### ISSUE TITLE
Tensorflow Hub: Support multi-GPU training in Keras or Estimator

### ISSUE THREAD

**Issue by rsethur** [tensorflow/hub#64] opened 2018-05-29 16:48 UTC
In my project I use Tf-Hub with estimators. However when I try to use multi GPU's (single machine) using tf.contrib.estimator.replicate_model_fn, I get the following error:

> variable_scope  was unused but the corresponding ". "name_scope was already taken.

Probably it is from this source line : [link](https://github.com/tensorflow/hub/blob/b94eb2bc236f486ae2cea51d22e43733c9c8967d/tensorflow_hub/module.py#L344)

Any help is much appreciated - received with thanks.

CC: @arnoegw

**Comment by arnoegw** [comment] 2018-05-30 09:33
Thanks for your report. Unfortunately, the straightforward way of instantiating a hub.Module in the model_fn of an Estimator does not currently work with tf.contrib.estimator.replicate_model_fn and how it calls the same model_fn repeatedly. To hack around this, one would have to to share hub.Module instances **for each graph** that model_fn gets called in (e.g., through a custom collection). After that, applying a Module object multiple times should basically just work.

If anyone else is hampered by this issue as well, please speak up here.

**Comment by rsethur** [comment] 2018-06-06 02:33
Hello @arnoegw , Can you please provide me more guidance/some pseudo code would help. Tf-Hub + Estimators have awesome potential for developers - ironing out these kinks would definitely help.

**Comment by arnoegw** [comment] 2018-06-06 15:31
I very much agree: it would be great to iron out the kinks that prevent straightforward use of Hub modules with multi-GPU Estimators. Unfortunately, at this time, I neither have that code, nor worked-out example code for the hack around that I sketched above. Sorry.

Leaving this open for the feature request...

**Comment by matthew-z** [comment] 2018-08-21 15:31
+1 The same problem.

 I also look forward to trying multiGPU with tf-hub

**Comment by akhilkatpally** [comment] 2018-09-25 17:49
+1 Same problem when using estimator, tf-hub with multi GPU.

**Comment by marhlder** [comment] 2018-11-19 14:46
Did anyone manage to conjure a working hack for this?

**Comment by marhlder** [comment] 2018-11-19 15:17
> Thanks for your report. Unfortunately, the straightforward way of instantiating a hub.Module in the model_fn of an Estimator does not currently work with tf.contrib.estimator.replicate_model_fn and how it calls the same model_fn repeatedly. To hack around this, one would have to to share hub.Module instances **for each graph** that model_fn gets called in (e.g., through a custom collection). After that, applying a Module object multiple times should basically just work.
> 
> If anyone else is hampered by this issue as well, please speak up here.

Where would the shared instance have to be created?

**Comment by edumotya** [comment] 2019-02-05 09:32
+1 I'm having the same problem using estimator, tf-hub with multi GPU(tf.contrib.distribute.MirroredStrategy()) .

**Comment by bjayakumar** [comment] 2019-02-07 17:05
Came here to report that it is still not fixed. I hope they fix it soon.

**Comment by hgadig** [comment] 2019-03-14 17:33
@arnoegw  Any update or ETA on this ?

**Comment by arnoegw** [comment] 2019-03-15 09:31
Hi all, thanks for your patience. We understand that multi-GPU training is important. While it was possible in low-level TensorFlow early on, its support by high-level frameworks has been a moving target. With the advent of TensorFlow 2 (see the recent [Dev Summit](https://www.youtube.com/playlist?list=PLQY2H8rRoyvzoUYI26kHmKSJBedn3SQuB)), both sides of the story are changing again, but for the better:

  * Hub modules for TF2 will be SavedModels in the TF2 version of that format, loaded natively
    with `tf.saved_model.load()`. Under the hood, this provides a clean separation of computation
    and state, which helps the cause.
  * [DistributionStrategy](https://github.com/tensorflow/community/blob/master/rfcs/20181016-replicator.md)
    is the new, more powerful abstraction for various kinds of parallel training.

So the TF2 version of this feature request is DistributionStrategy support for model pieces brought in by loading a SavedModel, preferably through Keras (not low-level TF). This is on the radar for the TensorFlow and TF Hub teams, but there is no specific timeline.

tf.contrib.estimator.replicate_model_fn is deprecated by now. We do not plan to go back and work on supporting it. Let me change the issue title accordingly....

**Comment by arnoegw** [comment] 2019-03-15 09:35
For those especially interested in retraining of image models faster than with retrain.py:

If you are ready to live on the cutting edge of TF 2.0.0alpha0, take a look at Hub's [examples/colab/tf2_image_retraining.ipynb](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb) which is considerably smaller, faster (if you use a GPU), and even supports fine-tuning the image module.

**Comment by gobrewers14** [comment] 2019-05-12 23:40
> Thanks for your report. Unfortunately, the straightforward way of instantiating a hub.Module in the model_fn of an Estimator does not currently work with tf.contrib.estimator.replicate_model_fn and how it calls the same model_fn repeatedly. To hack around this, one would have to to share hub.Module instances **for each graph** that model_fn gets called in (e.g., through a custom collection). After that, applying a Module object multiple times should basically just work.
> 
> If anyone else is hampered by this issue as well, please speak up here.

Really hampered by this issue.

```markdown
one would have to to share hub.Module instances **for each graph**
that model_fn gets called in
```
A little more detail on what is meant by that sentence would go along way.  Not asking for a solution but some pseudo-code could be great.

**Comment by r-wheeler** [comment] 2019-05-13 17:33
I am really hampered by this issue as well.

**Comment by rsethur** [comment] 2019-05-13 18:30
@arnoegw Many thanks for the development. Question: How is Hub positioned in comparison to the Keras applications models - seems to be quite similar. Will there be some unification in the future?
Also some of the models does not support fine tuning (object detection) - do you plan to fix this in future releases?

Thanks again!

**Comment by arnoegw** [comment] 2019-05-14 11:47
@rsethur: There are no plans for unification at this time. TF Hub overlaps with Keras Applications for the particular case of reusing CNNs for image classification / feature extraction, but TF Hub offers modules (sometimes entire models) for a number of other domains, and requires neither the module consumer nor the module publisher to use Keras.

**Comment by arnoegw** [comment] 2019-05-14 11:52
@gobrewers14, @r-wheeler: There is no great solution for TF1, but for TF2, there are the plans I described on March 15, and the already available [examples/colab/tf2_image_retraining.ipynb](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb) with decent fine-tuning performance on a single GPU. Hope that helps.

**Comment by littleDing** [comment] 2019-06-18 09:21
+1 I'm having the same problem using estimator, tf-hub with multi GPU(tf.contrib.distribute.MirroredStrategy()) .

**Comment by mhajiaghayi** [comment] 2019-06-27 01:44
I have the same problem with tf-hub and estimator and very disappointed by the response of tf team. sadly, one version to another, there are lots of changes in tensorflow.

**Comment by Aashish-1008** [comment] 2019-08-26 18:51
+1 
I'm having the same problem using estimator, 
tf-hub with multi GPU
**tf.contrib.distribute.MirroredStrategy(num_gpus=8) .**

**Comment by serdarbozoglan** [comment] 2019-10-18 13:38
I am also getting the same error: "RuntimeError: variable_scope module_8/ was unused but the corresponding name_scope was already taken."

**Comment by akshaydnicator** [comment] 2020-04-19 09:56
Still not fixed I believe. Please help!

RuntimeError: variable_scope module_3/ was unused but the corresponding name_scope was already taken.

Full Traceback:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-4a52df143d45> in <module>
      6 tf.compat.v1.disable_eager_execution()
      7 
----> 8 elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

/opt/conda/lib/python3.6/site-packages/tensorflow_hub/module.py in __init__(self, spec, trainable, name, tags)
    160       raise ValueError("No such graph variant: tags=%r" % tags)
    161 
--> 162     abs_state_scope = _try_get_state_scope(name, mark_name_scope_used=False)
    163     self._name = abs_state_scope.split("/")[-2]
    164 

/opt/conda/lib/python3.6/site-packages/tensorflow_hub/module.py in _try_get_state_scope(name, mark_name_scope_used)
    393       raise RuntimeError(
    394           "variable_scope %s was unused but the corresponding "
--> 395           "name_scope was already taken." % abs_state_scope)
    396   return abs_state_scope
    397 

RuntimeError: variable_scope module_3/ was unused but the corresponding name_scope was already taken.

**Comment by sbecon** [comment] 2020-08-26 02:58
I have the same issue

**Comment by frozenzo** [comment] 2020-12-30 05:54
Still hampered by the same issue for the time, is there any (hack) solution?

**Comment by arnoegw** [comment] 2021-02-11 10:12
This won't be fixed for TF1 and the libraries that target it (hub.Module, Estimator).

For TF2, Keras, and the TF2 SavedModels loaded from TF Hub with hub.KerasLayer, the usual way of building and compiling a Keras model under a tf.distribute.MirroredStrategy and then calling `.fit()`on a `tf.data.Dataset` should just work. What we don't have yet is a great example to demonstrate that, say, on a multi-GPU machine on Google Cloud.

**Comment by maringeo** [comment] 2021-06-11 15:20
TF Hub's `make_image_classifier` tool has been updated to use [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) and to demonstrate distributed training, including multi-GPU: https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier.

The `make_image_classifier` code is not a minimal working example, but as https://github.com/tensorflow/hub/issues/64#issuecomment-777335474 says, a Keras model build under [tf.distribute.MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy) that uses `tf.data.Dataset` should work on multi-GPU.

I plan to keep this issue open for a a few weeks, in case anyone encounters any issues that I've missed during testing.

**Closed** 2021-06-24 20:26 UTC
Labels: hub, stat:awaiting tensorflower, type:feature
