### ISSUE TITLE
error when retrain

### ISSUE THREAD

**Issue by weijjzhang** [tensorflow/hub#225] opened 2019-01-23 12:04 UTC
I train the model by my own image files, there is always error. Can you give me some suggestion?
The error is as below:
INFO:tensorflow:2019-01-23 19:57:43.403471: Step 3999: Train accuracy = 87.5%
INFO:tensorflow:2019-01-23 19:57:43.403624: Step 3999: Cross entropy = 0.180595
INFO:tensorflow:2019-01-23 19:57:43.424074: Step 3999: Validation accuracy = 92.0% (N=100)
2019-01-23 19:57:43.788535: W tensorflow/core/graph/graph_constructor.cc:1265] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Restoring parameters from /tmp/_retrain_checkpoint
Traceback (most recent call last):
  File "retrain.py", line 1315, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "retrain.py", line 1126, in main
    bottleneck_tensor)
  File "retrain.py", line 854, in run_final_eval
    ground_truth_input: test_ground_truth
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor u'input/BottleneckInputPlaceholder:0', which has shape '(?, 1024)'

The images has no problem. Even I use the images download from network: flower_photos. The error is the same.
My tensorflow version is 1.12.0 and tensorflow-hub version is tensorflow-hub-0.2.0.
And the command is as below:
python retrain.py \
    --image_dir /home/zw/work/tensorflow/hub/examples/image_retraining/dataset/ \
    --output_graph  /home/zw/work/tensorflow/hub/examples/image_retraining/tmp/output_graph.pb \
    --intermediate_output_graphs_dir /home/zw/work/tensorflow/hub/examples/image_retraining/tmp/intermediate_graph \
    --output_labels /home/zw/work/tensorflow/hub/examples/image_retraining/tmp/output_labels.txt \
    --intermediate_store_frequency 1000 \
    --testing_percentage 0 \
    --how_many_training_steps 4000 \
    --learning_rate 0.001  \
    --train_batch_size 8 \
    --tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1 \      
    --saved_model_dir /home/zw/work/tensorflow/hub/examples/image_retraining/tmp/myModel

**Comment by gameon67** [comment] 2019-01-28 01:55
But you got the result
```
INFO:tensorflow:2019-01-23 19:57:43.403471: Step 3999: Train accuracy = 87.5%
INFO:tensorflow:2019-01-23 19:57:43.403624: Step 3999: Cross entropy = 0.180595
INFO:tensorflow:2019-01-23 19:57:43.424074: Step 3999: Validation accuracy = 92.0% (N=100)
```

**Comment by hgadig** [comment] 2019-03-11 22:33
Your input BottleneckInputPlaceholder is of shape (?, 1024)
The problem is that you're feeding the placeholder with a value of a different shape. Please make sure you are feeding it with the same shape and retry by reshaping the image.

**Comment by hgadig** [comment] 2019-03-18 22:54
Closing as it is in "awaiting response" status for more than 3 days. Feel free to add your comments and we will reopen.

**Closed by hgadig** 2019-03-18 22:54 UTC
Labels: hub, stat:awaiting response, subtype:Image Retraining, type:support
