### ISSUE TITLE
merge  preprocess model and bert model  to one but  can't find vocab.txt file

### ISSUE THREAD

**Issue by BookChan** [tensorflow/hub#721] opened 2021-01-12 11:12 UTC
# What have I done
1. download bert pretrained model and preprocess model
2. build a new  keras model  that accepts text input and output bert transformer embedding
3. Save the new model and shift it to another machine
4. In another machine, we load the new keras model but gets error `FileNotFoundError:  /cache/bert_multi_cased_preprocess_2/assets/vocab.txt; No such file or directory`

```python
# model can be downloaded  from `pretrain_model url`
preprocess_model_path = "/cache/bert_multi_cased_preprocess_2"
pretrained_model_path = "/cache/bert_multi_cased_L-12_H-768_A-12" 
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer( preprocess_model_path)
encoder_inputs = preprocessor(text_input)
encoder = hub.KerasLayer(
         pretrained_model_path,
    trainable=True)
outputs = encoder(encoder_inputs)
model = keras.Model(
        inputs=text_input, outputs=outputs)
model.save("/tmp/bert_with_preprocess/")
```
In another machine that hasn't `/cache/bert_multi_cased_preprocess_2` folder,but we have 
`vocab.txt` in `/tmp/bert_with_preprocess/assets/`
```python
model = hub.KerasLayer("/tmp/bert_with_preprocess/")
# FileNotFoundError:  /cache/bert_multi_cased_preprocess_2/assets/vocab.txt; No such file or directory
```
# What I expect
The new keras model holds everything, and can be shifted  and running everywhere.  
But, it seems that keras layer keeps the old model assets path , and doesn't set to the new model assets path.

# pretrain_model url
[bert_multi_cased_L-12_H-768_A-12](https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3)
[bert_multi_cased_preprocess](https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/2)

**Comment by PradipNichite** [comment] 2021-01-16 05:05
is anyone working on this? I would like to work

**Comment by arnoegw** [comment] 2021-01-28 10:32
Duplicate of https://github.com/tensorflow/hub/issues/719

To fix, please update to https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3

BTW, we recommend to use tfhub.dev URLs in your code directly, see https://www.tensorflow.org/hub/caching for how it works and how to control it.

**Comment by arnoegw** [comment] 2021-01-28 10:33
Duplicate of https://github.com/tensorflow/hub/issues/719

**Closed** 2021-01-28 10:33 UTC
Labels: stat:awaiting tensorflower, subtype:Keras, subtype:text-embedding, type:others
