### ISSUE TITLE
Feature request: use Hub modules with Eager execution enabled

### ISSUE THREAD

**Issue by nathanin** [tensorflow/hub#124] opened 2018-08-01 03:42 UTC
Hi, I guess this is best classified as a support request. I'm trying to use a Hub resnet image model in a transfer learning application. Most of my project takes advantage of tensorflow's eager execution mode. When I add in the image module, I am met with the following error, below, at the line that should download and import the module (is inside of a `tfe.Network.__init__()` method.).

The main message is pretty straightforward: that no graph exists for eager mode therefore the Hub module graph cannot be imported. Is there a way around this.. or will I have to dump the variables to a `npy` and use them to initialize eager tensors?

```
Traceback (most recent call last):
  File "run.py", line 170, in <module>
    main(train_list, val_list, test_list, Model, loss_function, arch_dir, fold_num)
  File "run.py", line 75, in main
    model = Model()
  File "/home/.../script.py", line 32, in __init__
    self.resnet = hub.Module(MODULE_URL, trainable=True, tags={'train'})
  File "/home/ing/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow_hub/module.py", line 126, in __init__
    tags=self._tags)
  File "/home/ing/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow_hub/native_module.py", line 282, in _create_impl
    name=name)
  File "/home/ing/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow_hub/native_module.py", line 333, in __init__
    variable_tensor_map, self._state_map = self._create_state_graph(name)
  File "/home/ing/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow_hub/native_module.py", line 383, in _create_state_graph
    restore_collections_predicate=(lambda key: key in import_collections))
  File "/home/ing/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1943, in import_meta_graph
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.
```

Some information about my environment:
```
$ pip freeze | grep tensorflow
tensorflow==1.8.0
tensorflow-gpu==1.7.0
tensorflow-hub==0.1.0
tensorflow-tensorboard==1.5.0

$ python --version
Python 2.7.12
```

**Comment by mynameisguy** [comment] 2018-08-15 12:52
+1 for the request

**Comment by zixia** [comment] 2018-10-05 06:16
+1 for the request

**Comment by gokul-uf** [comment] 2018-10-19 12:17
@arnoegw considering that Eager would be the default execution mode from TF 2 and upwards, wouldn't this feature request be more than just a "nice thing to have" ?

**Comment by arnoegw** [comment] 2018-10-19 14:08
@gokul-uf: Agreed. We are working on TF2 support, including Eager mode, in time for the TF2.0 release (not preview).

**Comment by gokul-uf** [comment] 2018-10-19 16:56
Thanks for the update @arnoegw  For those who can't wait until until TF2, I believe `tfe.py_func` might be a nice intermediate. Hacky, yes. But it works. See [here](https://www.tensorflow.org/guide/eager#use_eager_execution_in_a_graph_environment) for an example

**Comment by Selimonder** [comment] 2019-01-25 16:54
+1 for this

**Comment by leemengtaiwan** [comment] 2019-03-22 04:46
Looking forward for this. 

I'm a early TF 2.0 adapter but can't figure how to use TF Hub within TF 2.0 preview version.

**Comment by arnoegw** [comment] 2019-03-25 10:41
@leemengtaiwan: For guiding examples, please see
https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_text_classification.ipynb
https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb

**Comment by rmothukuru** [comment] 2019-04-22 08:46
Closing this Feature Request as we can use Hub Modules with Eager Execution Enabled from Tensorflow 2.0 Alpha version on wards. Please feel free to reopen this issue if your requirement is not implemented.

**Comment by Aashish-1008** [comment] 2019-04-30 07:08
+1 for this

**Comment by amitness** [comment] 2019-07-06 13:41
+1

**Comment by shishirmane** [comment] 2019-10-02 07:04
I checked with the recently released tensorflow 2.0.0 (stable), the issue is still persisting.

I tried it for accessing the ELMo vectors using the following tensorflow-hub line:
elmo_model = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

Exception:
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

**Comment by arnoegw** [comment] 2019-10-02 09:12
Please use
```
elmo_model = hub.load("https://tfhub.dev/google/elmo/2")
out = elmo_model.signatures["default"](in)
```
...optionally with a tf.GradientTape() around the call.

In TF2, `hub.load()` is the right API to use for both TF1-style Hub modules and TF2-style SavedModels. All it does is fetch the model contents into TFHUB_CACHE_DIR and then call `tf.saved_model.load()` from there.

Moe detailed documentation on TF Hub will be forthcoming. For TF2-style SavedModels in general, please see https://www.tensorflow.org/guide/saved_model

**Comment by federicoruggeri** [comment] 2019-10-07 10:49
Hello, 
I've just tried the following:

```
import tensorflow as tf
import tensorflow_hub as hub

elmo = hub.load('https://tfhub.dev/google/elmo/2')
test_input = tf.constant(['the cat is on the table'], dtype=tf.string)

with tf.GradientTape() as tape:
    result = elmo.signatures['default'](test_input)
```

And it throws **AttributeError: 'NoneType' object has no attribute 'outer_context'** when calling the loaded ELMo model. On the other hand, removing the `tf.GradientTape()` wrap up, the code works. Am I missing something?

```
elmo = hub.load('https://tfhub.dev/google/elmo/2')
test_input = tf.constant(['the cat is on the table'], dtype=tf.string)
result = elmo.signatures['default'](test_input)
```

**Tensorflow config:**
tensorflow-estimator==2.0.0
tensorflow-gpu==2.0.0
tensorflow-hub==0.6.0

**Python config:**
Python 3.5.3

**Comment by ReemSuwaileh** [comment] 2019-10-26 17:15
+1 for the request

**Comment by Carolyn95** [comment] 2019-11-05 05:39
+1 for the request.
I tried load USE module using these lines:
```python
use_module = hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/3")
def embed_use(self, x):
        return self.use_model(tf.reshape(tf.cast(x, 'string'), [-1]), signature='default', as_dict=True)['default']
```
but got `TypeError: 'AutoTrackable' object is not callable`

my config:
- Python  == 3.7.2
- tensorflow_hub == 0.7.0
- tensorflow == 2.0.0

**Comment by arnoegw** [comment] 2019-11-13 08:43
@ReemSuwaileh: For TF2 versions of BERT, please see the new models https://tfhub.dev/s?publisher=tensorflow&q=bert published from the reimplementation of BERT from tensorflow/models.

**Comment by arnoegw** [comment] 2019-11-13 08:47
@Carolyn95: To get the TF2 version of google/universal-sentence-encoder-large, please upgrade to https://tfhub.dev/google/universal-sentence-encoder-large/4 

For using old models in the hub.Module format with hub.load(), please see https://www.tensorflow.org/hub/migration_tf2 and notice how the signature is picked out from a dict (not passed as an argument).

**Comment by arnoegw** [comment] 2019-11-13 09:22
@federicoruggeri: Thanks for reporting the problem about tf.GradientTape and the elmo model. This is important but distinct enough to be tracked separately. I filed it as https://github.com/tensorflow/hub/issues/416

**Comment by arnoegw** [comment] 2019-11-13 09:24
The original feature request has been fulfilled. Please file separate issues if you encounter any problems besides the ones addressed above. Thank you.

**Closed by arnoegw** 2019-11-13 09:24 UTC
Labels: hub, stat:awaiting tensorflower, type:feature
