### ISSUE TITLE
Error 404 when download module 

### ISSUE THREAD

**Issue by wudixiaop** [tensorflow/hub#159] opened 2018-09-17 02:11 UTC
Hi, 

Below is the error log. I also tried using curl -L "https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1", and got same results.

----------
INFO:tensorflow:Using /var/folders/zp/3lp0dtb95l57nh2cz0zppggc0000gn/T/tfhub_modules to cache modules.
INFO:tensorflow:Downloading TF-Hub Module 'https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1'.
Traceback (most recent call last):
  File "hub/examples/image_retraining/retrain.py", line 1314, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "hub/examples/image_retraining/retrain.py", line 998, in main
    module_spec = hub.load_module_spec(FLAGS.tfhub_module)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 99, in load_module_spec
    path = compressed_module_resolver.get_default().get_module_path(path)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 385, in get_module_path
    return self._get_module_path(handle)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 467, in _get_module_path
    return resolver.get_module_path(handle)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 385, in get_module_path
    return self._get_module_path(handle)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 105, in _get_module_path
    self._lock_file_timeout_sec())
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 313, in atomic_download
    download_fn(handle, tmp_dir)
  File "/Developer/Labs/AI/Tensorflow/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 101, in download
    response = url_opener.open(request)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by deepam1803** [comment] 2018-09-17 02:38
module_url = "https://tfhub.dev/google/universal-sentence-encoder/2" 

Got same error for the above module.

**Comment by vbardiovskyg** [comment] 2018-09-17 09:04
Hi, the issue should be resolved now, could you please try again?

**Comment by wudixiaop** [comment] 2018-09-17 09:09
@vbardiovskyg I tested it and it works now. Thank you!

**Comment by TanLingxiao** [comment] 2018-09-17 14:33
It can be solved from here:
[https://github.com/tensorflow/hub/blob/master/docs/common_issues.md](https://github.com/tensorflow/hub/blob/master/docs/common_issues.md)

**Comment by XuSShuai** [comment] 2018-09-22 00:42
> It can be solved from here:
> https://github.com/tensorflow/hub/blob/master/docs/common_issues.md

The two line codes below  is work for me, but when I execute the `retrain.py`, it's still need to download the module and always failed, why? 
```python
 import tensorflow_hub as hub
 hub.Module("/tmp/moduleA")
```

**Comment by TanLingxiao** [comment] 2018-09-25 02:08
Maybe the problem is the internet error.When using the model,it will download the model file in /tmp/tfhub, so you can download the model by yourself first.

**Comment by XuSShuai** [comment] 2018-09-27 10:35
> Maybe the problem is the internet error.When using the model,it will download the model file in /tmp/tfhub, so you can download the model by yourself first.
> Please refer here :#53

I have already download the module, and uncompress it by the code below to the folder `/tmp/moduleA`
```python
curl -L "https://tfhub.dev/google/universal-sentence-encoder/2?tf-hub-format=compressed" | tar -zxvC /tmp/moduleA
```
but it seem can not find this model and keep going to download from internet when i run the `retrain.py`

**Comment by andresusanopinto** [comment] 2018-10-02 11:56
The original reported issue has been fixed. Closing this issue.

Thanks @TanLingxiao to provide extra help to the issue from @XuSShuai.

**Closed by andresusanopinto** 2018-10-02 11:56 UTC
