### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry.

### ISSUE THREAD

**Issue by ntaherkhani** [tensorflow/hub#419] opened 2019-11-15 19:59 UTC
I am trying to creat tensorflow-hub Module using locally saved ALBER pre-trained model and I am getting this error :
 tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry.
I have:
tensorflow: 1.14.0
tensorflow-hub: 0.7.0
opt-einsum= 3.1.0
I am working on MAC OS High Sierra 10.13.6

**Comment by rmothukuru** [comment] 2019-11-18 05:50
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ntaherkhani** [comment] 2019-11-18 13:09
@rmothukuru thanks for your response. 
this is the code for creating module:
import tensorflow_hub as hub
import tensorflow as tf
embed= hub.Module(“/path/to/saved/locally/pre-trained/ALBERT/Model/ALBERT_xxlarge")


this is the error that I got
Traceback (most recent call last):
  File "/Users/……/python/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Users/……/python/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/……/python/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/……/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/…….py", line 3, in <module>
    embed= hub.Module("/Users/……/Pretrain models/ALBERT/ALBERT_xxlarge")
File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/module.py", line 176, in __init__
    tags=self._tags)
  File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 386, in _create_impl
    name=name)
  File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 428, in __init__
    op.name for op in self._meta_graph.meta_info_def.stripped_op_list.op})
  File "/Users/……/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 858, in register_ops_if_needed
    "the c++ registry." % missing_ops)
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry.

I downloaded pre-trained ALBERT model from:
https://tfhub.dev/google/albert_xxlarge/2?tf-hub-format=compressed

thanks.

**Comment by rmothukuru** [comment] 2019-11-19 04:12
Could reproduce the error with TF Version 1.14, TF Hub Version 0.7 and opt-einsum version 3.1.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/b45e77cd448924ead5b4bef56841acba/hub_419_albert.ipynb#scrollTo=Msq9hLdL1Xi7). Thanks!

**Comment by j-grimstad** [comment] 2019-11-19 13:05
@ntaherkhani Thanks for using TF Hub!

Adding an import statement to import numpy appears to fix the immediate issue -- see [this Gist](https://colab.sandbox.google.com/gist/j-grimstad/0b98f0686c9c5e06c32916cd6e91422a/hub_419_albert.ipynb). 

Please take a look and comment back on this thread in case that doesn't fix the issue.

**Comment by ntaherkhani** [comment] 2019-11-19 13:34
@j-grimstad thanks for your response . 
I imported numpy but didnt help.

**Comment by j-grimstad** [comment] 2019-11-19 14:47
@ntaherkhani 

Turns out this model only works with TF 1.15 installed -- see [Gist](https://colab.sandbox.google.com/gist/j-grimstad/28f3845dedb8869b11305f00a6dcac58/hub_419_albert.ipynb). 

I'll get in contact with the model owner to make sure this is clear in the model documentation going forward. Please let me know if this fixes the issue.

**Comment by ntaherkhani** [comment] 2019-11-19 15:31
@j-grimstad thanks for your solution.
I upgraded my Tensorflow to 1.15 and it is working now and I can create  hub Module for pre-trained ALBERT V1 and V2 models. 
however, when I am trying to embed the textual data and create feature vector using following code:
embeddings=embed(["sample of textual data."])
I am getting error  "ValueError: Signature 'default' is missing from meta graph."

**Comment by j-grimstad** [comment] 2019-12-02 15:38
@ntaherkhani 

Take a closer look at the "Example Use" section in https://tfhub.dev/google/albert_xxlarge/2, specifically, you'll need to specify signatures='tokens'.

The longer form demonstration also is useful (see beginning line 54 for where to specify signature='tokens' within the larger workflow): https://github.com/google-research/google-research/blob/master/albert/run_classifier_with_tfhub.py

I'll close this bug for now, since you're running into intended errors thus far -- if you need help with error troubleshooting, you'll likely receive timelier responses on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow-hub).

**Closed by j-grimstad** 2019-12-02 15:38 UTC
Labels: stat:awaiting tensorflower, subtype:text-embedding, type:bug

**Comment by DarrVeter** [comment] 2019-12-06 11:20
use tensorflow version 1.15

**Comment by Shivan11** [comment] 2020-10-28 16:13
@ntaherkhani Were you able to resolve this issue ? Cant seem to find a solution for this. I tried adding signature='tokens' but it gives me a "Signature expects multiple inputs. Use a dict." error

**Comment by valexandersaulys** [comment] 2020-11-28 20:14
I'm running tensorflow 1.15.4 via Docker and _still_ get this error

Note that I do have to install tensorflow hub outside of this to run it at all.
