### ISSUE TITLE
Training bert on 1 machine with 8 v100s throws `Trying to access a placeholder that is not supposed to be executed`

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/hub#649] opened 2020-07-31 02:18 UTC
Load the hub under a mirrored strategy and training a classification algorithm. This model is trained on 8 v100 gpus in google cloud by submitting a docker container to google cloud machine learning engine.
```
... 
strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    model = MyModel() # uses hub.KerasLayer layer to load bert multi lingual 
    model.fit(..)             # explodes 

```

Relevant part of the trace, in which you can see it is a node under the bert embeddings 
```
Traceback (most recent call last):
...
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [Trying to access a placeholder that is not supposed to be executed. This means you are executing a graph generated from the cross-replica context in an in-replica context.]
     [[{{node bert_embeddings/keras_layer/StatefulPartitionedCall/Assert/Assert}}]]
     [[cond/else/_144/Maximum/_388]]
  (1) Invalid argument:  assertion failed: [Trying to access a placeholder that is not supposed to be executed. This means you are executing a graph generated from the cross-replica context in an in-replica context.]
     [[{{node bert_embeddings/keras_layer/StatefulPartitionedCall/Assert/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_call_240207]

Function call stack:
call -> call
```

Possibly related to #515

**Comment by r-wheeler** [comment] 2020-08-01 16:10
After looking further at the stack trace this looks like it was not coming from .fit but predict / eval being ran under the context manager.

**Comment by gowthamkpr** [comment] 2020-08-06 17:54
@r-wheeler Yes this does look like a duplicate of #515 Lets close this issue and track it in issue #515. Let me know if you think otherwise. Thanks!

**Closed** 2020-08-12 19:33 UTC
Labels: stat:awaiting response, subtype:text-embedding, type:bug
