### ISSUE TITLE
Feature request: ability to export a hub module from a feature column

### ISSUE THREAD

**Issue by choran** [tensorflow/hub#132] opened 2018-08-10 11:40 UTC
Hi, 
I just wanted to open a new issue about this just to clarify in case i am doing something obviously wrong and it can be closed quickly rather than adding to another issue:

I am using the classifier example [here](https://colab.research.google.com/github/tensorflow/hub/blob/master/docs/tutorials/text_classification_with_tf_hub.ipynb#scrollTo=25rdoEHih0fm) with the USE module and setting the trainable parameter to True.
I then want to check the embeddings that are generated by my new retrained weights. But I cannot seem to do this.

I am getting the classifier to work but then I am unable to use the retrained model after wards to generate new embeddings. Do I have to explicitly save the new module somehow in order to use it after the classifier code has finished running? If I point to the USE module after training should it now generate embeddings with the new weights or do I need to save a new module during the training?

I just wanst sure if I had to explicitly save my new module in case I wanted to use it in future to generate retrained embeddings?
Thanks in advance
Cathal

**Comment by vbardiovskyg** [comment] 2018-08-28 09:16
Hi,

the fine-tuned module will have to exported for later reuse, unfortunately we currently have no way of exporting a module from a Canned Estimator with feature_columns.

The simplest thing in this case is to write your own [custom estimator](https://www.tensorflow.org/guide/custom_estimators) and inside the model_fn, call the module directly, for example:
```
hub_module = hub.Module(spec)
hub.register_module_for_export(hub_module, "my_module")

embedding = hub_module(features["text"])
first_layer = tf.layers.dense(inputs=embedding, units=100, activation=tf.nn.relu)
second_layer = tf.layers.dense(inputs=first_layer, units=100, activation=tf.nn.relu)
logits = tf.layers.dense(inputs=second_layer, units=1, activation=None)
predictions = tf.sigmoid(logits)
```

Exporting from a custom estimator is well documented for example in this [test](https://github.com/tensorflow/hub/blob/2bd67f1df78c7d465254c3e21e96d8782b37d653/tensorflow_hub/estimator_test.py#L85).

I will keep this issue open until we make direct export from feature columns possible.

**Comment by choran** [comment] 2018-08-28 12:51
@vbardiovskyg thanks for the update, that is super helpful. I was running into problems using the canned estimator feature columns so I figured that I needed to create my own custom estimator. Its great to have this confirmed so appreciate that.
I need to spend more time just getting more familiar with creating a custom estimator since it was not something I had previously implemented in TF. So the example code here is really helpful to point me in the right direction.

**Comment by rmothukuru** [comment] 2019-06-07 05:18
Closing this issue as it has been resolved.

**Comment by meethariprasad** [comment] 2019-11-26 07:09
Is this feature added? Can we know with a example on how to export fine tuned USE module for reuse?

**Comment by vbardiovskyg** [comment] 2019-11-26 09:48
Let's keep this feature request open since it has not been added yet.

**Comment by meethariprasad** [comment] 2019-11-29 11:03
> @vbardiovskyg thanks for the update, that is super helpful. I was running into problems using the canned estimator feature columns so I figured that I needed to create my own custom estimator. Its great to have this confirmed so appreciate that.
> I need to spend more time just getting more familiar with creating a custom estimator since it was not something I had previously implemented in TF. So the example code here is really helpful to point me in the right direction.

Can you please share your code where you have worked any solution for this?

**Comment by meethariprasad** [comment] 2019-11-29 14:56
> embedding = hub_module(features["text"])

Hi @vbardiovskyg , I tried your suggestion. I am getting following None values not supported error during export. Can you please help? Following is the reproducible code in TFHub1

```
import tensorflow as tf
from tensorflow.keras.models import Model
import tensorflow_hub as hub

_TEXT_FEATURE_NAME = "text"
_EXPORT_MODULE_NAME = "unifinetune"

uni_sent_module_path="https://tfhub.dev/google/nnlm-en-dim128-with-normalization/1"

def _input_fn():
    """An input fn."""
    features = {
        _TEXT_FEATURE_NAME: tf.constant([
          "hadoop hive", "asp net","js javascript nodejs"]),
    }
    labels = tf.constant([0,1,2])
    return features, labels


def _serving_input_fn():
    """A serving input fn."""
    text_features = tf.placeholder(dtype=tf.string, shape=[None])
    return tf.estimator.export.ServingInputReceiver(
        features={_TEXT_FEATURE_NAME: text_features},
        receiver_tensors=text_features)

def _get_model_fn(register_module=False):
#     mode=tf.estimator.ModeKeys.TRAIN
    def _model_fn(features, labels, mode):
        """A model_fn that uses a mock TF-Hub module."""
#         del labels
        
        hub_module = hub.Module(uni_sent_module_path,trainable=True)
        hub.register_module_for_export(hub_module, "my_module")

        embedding = hub_module(features["text"])
        print (embedding.shape)
        first_layer = tf.layers.dense(inputs=embedding, units=100, activation=tf.nn.relu)
        second_layer = tf.layers.dense(inputs=first_layer, units=100, activation=tf.nn.relu)
        logits = tf.layers.dense(inputs=second_layer, units=3, activation=None)
        predictions = tf.argmax(logits, 1)
        labels = tf.cast(labels, tf.int64)
        print (labels.shape,logits.shape,predictions.shape)
        
        loss = tf.losses.sparse_softmax_cross_entropy(labels,logits)
        # Create an optimizer that will take care of the Gradient Descent
        optimizer = tf.train.AdamOptimizer(0.01)

        # Create the training operation
        train_op = optimizer.minimize(loss,tf.train.get_global_step())

        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions=predictions,
            loss=loss,
            train_op=train_op)
    return _model_fn

import os
os.makedirs("modeldir", exist_ok=True)
os.makedirs("export", exist_ok=True)
model_dir = os.path.join(os.getcwd(),'modeldir')
export_base_dir = os.path.join(os.getcwd(), "export")
estimator = tf.estimator.Estimator(_get_model_fn(register_module=True),
                                       model_dir=model_dir)
estimator.train(input_fn=_input_fn, steps=10)
exporter = hub.LatestModuleExporter("exporter_name", _serving_input_fn)
export_dir = exporter.export(estimator=estimator,export_path=export_base_dir,checkpoint_path=estimator.latest_checkpoint())
```
```
Error

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_num_ps_replicas': 0, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', '_train_distribute': None, '_save_checkpoints_secs': 600, '_is_chief': True, '_model_dir': '/media/sf_codebase/experiment/modeldir', '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_master': '', '_eval_distribute': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f2ad43bf6a0>, '_task_type': 'worker', '_save_summary_steps': 100, '_global_id_in_cluster': 0, '_device_fn': None, '_service': None, '_keep_checkpoint_max': 5, '_task_id': 0, '_experimental_distribute': None, '_log_step_count_steps': 100, '_protocol': None, '_tf_random_seed': None, '_num_worker_replicas': 1, '_save_checkpoints_steps': None}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
(?, 128)
(3,) (?, 3) (?,)
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /media/sf_codebase/experiment/modeldir/model.ckpt-20
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 20 into /media/sf_codebase/experiment/modeldir/model.ckpt.
INFO:tensorflow:loss = 0.0, step = 21
INFO:tensorflow:Saving checkpoints for 30 into /media/sf_codebase/experiment/modeldir/model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
(?, 128)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-3124196a4b17> in <module>()
    100 estimator.train(input_fn=_input_fn, steps=10)
    101 exporter = hub.LatestModuleExporter("exporter_name", _serving_input_fn)
--> 102 export_dir = exporter.export(estimator=estimator,export_path=export_base_dir,checkpoint_path=estimator.latest_checkpoint())
    103 #eval_result=None,is_the_final_export=None

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow_hub/estimator.py in export(self, estimator, export_path, checkpoint_path, eval_result, is_the_final_export)
    149 
    150     session = _make_estimator_serving_session(estimator, self._serving_input_fn,
--> 151                                               checkpoint_path)
    152     with session:
    153       export_modules = tf.get_collection(_EXPORT_MODULES_COLLECTION)

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow_hub/estimator.py in _make_estimator_serving_session(estimator, serving_input_fn, checkpoint_path)
    195         labels=None,
    196         mode=mode,
--> 197         config=estimator.config)
    198 
    199     # pylint: disable=protected-access

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py in public_model_fn(features, labels, mode, config)
    233 
    234     def public_model_fn(features, labels, mode, config):
--> 235       return self._call_model_fn(features, labels, mode, config)
    236 
    237     return public_model_fn

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
   1193 
   1194     logging.info('Calling model_fn.')
-> 1195     model_fn_results = self._model_fn(features=features, **kwargs)
   1196     logging.info('Done calling model_fn.')
   1197 

<ipython-input-41-3124196a4b17> in _model_fn(features, labels, mode)
     64         logits = tf.layers.dense(inputs=second_layer, units=3, activation=None)
     65         predictions = tf.argmax(logits, 1)
---> 66         labels = tf.cast(labels, tf.int64)
     67         print (labels.shape,logits.shape,predictions.shape)
     68 

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py in cast(x, dtype, name)
    673       # allows some conversions that cast() can't do, e.g. casting numbers to
    674       # strings.
--> 675       x = ops.convert_to_tensor(x, name="x")
    676       if x.dtype.base_dtype != base_type:
    677         x = gen_math_ops.cast(x, base_type, name=name)

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, preferred_dtype)
   1048       name=name,
   1049       preferred_dtype=preferred_dtype,
-> 1050       as_ref=False)
   1051 
   1052 

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
   1144 
   1145     if ret is None:
-> 1146       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1147 
   1148     if ret is NotImplemented:

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    227                                          as_ref=False):
    228   _ = as_ref
--> 229   return constant(v, dtype=dtype, name=name)
    230 
    231 

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    206   tensor_value.tensor.CopyFrom(
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    210   const_tensor = g.create_op(

/opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    428   else:
    429     if values is None:
--> 430       raise ValueError("None values not supported.")
    431     # if dtype is provided, forces numpy array to be the type
    432     # provided if possible.

ValueError: None values not supported.


```

**Comment by meethariprasad** [comment] 2019-11-29 16:21
> > embedding = hub_module(features["text"])
> 
> Hi @vbardiovskyg , I tried your suggestion. I am getting following None values not supported error during export. Can you please help? Following is the reproducible code in TFHub1
> 
> ```
> import tensorflow as tf
> from tensorflow.keras.models import Model
> import tensorflow_hub as hub
> 
> _TEXT_FEATURE_NAME = "text"
> _EXPORT_MODULE_NAME = "unifinetune"
> 
> uni_sent_module_path="https://tfhub.dev/google/nnlm-en-dim128-with-normalization/1"
> 
> def _input_fn():
>     """An input fn."""
>     features = {
>         _TEXT_FEATURE_NAME: tf.constant([
>           "hadoop hive", "asp net","js javascript nodejs"]),
>     }
>     labels = tf.constant([0,1,2])
>     return features, labels
> 
> 
> def _serving_input_fn():
>     """A serving input fn."""
>     text_features = tf.placeholder(dtype=tf.string, shape=[None])
>     return tf.estimator.export.ServingInputReceiver(
>         features={_TEXT_FEATURE_NAME: text_features},
>         receiver_tensors=text_features)
> 
> def _get_model_fn(register_module=False):
> #     mode=tf.estimator.ModeKeys.TRAIN
>     def _model_fn(features, labels, mode):
>         """A model_fn that uses a mock TF-Hub module."""
> #         del labels
>         
>         hub_module = hub.Module(uni_sent_module_path,trainable=True)
>         hub.register_module_for_export(hub_module, "my_module")
> 
>         embedding = hub_module(features["text"])
>         print (embedding.shape)
>         first_layer = tf.layers.dense(inputs=embedding, units=100, activation=tf.nn.relu)
>         second_layer = tf.layers.dense(inputs=first_layer, units=100, activation=tf.nn.relu)
>         logits = tf.layers.dense(inputs=second_layer, units=3, activation=None)
>         predictions = tf.argmax(logits, 1)
>         labels = tf.cast(labels, tf.int64)
>         print (labels.shape,logits.shape,predictions.shape)
>         
>         loss = tf.losses.sparse_softmax_cross_entropy(labels,logits)
>         # Create an optimizer that will take care of the Gradient Descent
>         optimizer = tf.train.AdamOptimizer(0.01)
> 
>         # Create the training operation
>         train_op = optimizer.minimize(loss,tf.train.get_global_step())
> 
>         return tf.estimator.EstimatorSpec(
>             mode=mode,
>             predictions=predictions,
>             loss=loss,
>             train_op=train_op)
>     return _model_fn
> 
> import os
> os.makedirs("modeldir", exist_ok=True)
> os.makedirs("export", exist_ok=True)
> model_dir = os.path.join(os.getcwd(),'modeldir')
> export_base_dir = os.path.join(os.getcwd(), "export")
> estimator = tf.estimator.Estimator(_get_model_fn(register_module=True),
>                                        model_dir=model_dir)
> estimator.train(input_fn=_input_fn, steps=10)
> exporter = hub.LatestModuleExporter("exporter_name", _serving_input_fn)
> export_dir = exporter.export(estimator=estimator,export_path=export_base_dir,checkpoint_path=estimator.latest_checkpoint())
> ```
> 
> ```
> Error
> 
> INFO:tensorflow:Using default config.
> INFO:tensorflow:Using config: {'_num_ps_replicas': 0, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', '_train_distribute': None, '_save_checkpoints_secs': 600, '_is_chief': True, '_model_dir': '/media/sf_codebase/experiment/modeldir', '_session_config': allow_soft_placement: true
> graph_options {
>   rewrite_options {
>     meta_optimizer_iterations: ONE
>   }
> }
> , '_master': '', '_eval_distribute': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f2ad43bf6a0>, '_task_type': 'worker', '_save_summary_steps': 100, '_global_id_in_cluster': 0, '_device_fn': None, '_service': None, '_keep_checkpoint_max': 5, '_task_id': 0, '_experimental_distribute': None, '_log_step_count_steps': 100, '_protocol': None, '_tf_random_seed': None, '_num_worker_replicas': 1, '_save_checkpoints_steps': None}
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Saver not created because there are no variables in the graph to restore
> (?, 128)
> (3,) (?, 3) (?,)
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Create CheckpointSaverHook.
> INFO:tensorflow:Graph was finalized.
> INFO:tensorflow:Restoring parameters from /media/sf_codebase/experiment/modeldir/model.ckpt-20
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> INFO:tensorflow:Saving checkpoints for 20 into /media/sf_codebase/experiment/modeldir/model.ckpt.
> INFO:tensorflow:loss = 0.0, step = 21
> INFO:tensorflow:Saving checkpoints for 30 into /media/sf_codebase/experiment/modeldir/model.ckpt.
> INFO:tensorflow:Loss for final step: 0.0.
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Saver not created because there are no variables in the graph to restore
> (?, 128)
> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-41-3124196a4b17> in <module>()
>     100 estimator.train(input_fn=_input_fn, steps=10)
>     101 exporter = hub.LatestModuleExporter("exporter_name", _serving_input_fn)
> --> 102 export_dir = exporter.export(estimator=estimator,export_path=export_base_dir,checkpoint_path=estimator.latest_checkpoint())
>     103 #eval_result=None,is_the_final_export=None
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow_hub/estimator.py in export(self, estimator, export_path, checkpoint_path, eval_result, is_the_final_export)
>     149 
>     150     session = _make_estimator_serving_session(estimator, self._serving_input_fn,
> --> 151                                               checkpoint_path)
>     152     with session:
>     153       export_modules = tf.get_collection(_EXPORT_MODULES_COLLECTION)
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow_hub/estimator.py in _make_estimator_serving_session(estimator, serving_input_fn, checkpoint_path)
>     195         labels=None,
>     196         mode=mode,
> --> 197         config=estimator.config)
>     198 
>     199     # pylint: disable=protected-access
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py in public_model_fn(features, labels, mode, config)
>     233 
>     234     def public_model_fn(features, labels, mode, config):
> --> 235       return self._call_model_fn(features, labels, mode, config)
>     236 
>     237     return public_model_fn
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
>    1193 
>    1194     logging.info('Calling model_fn.')
> -> 1195     model_fn_results = self._model_fn(features=features, **kwargs)
>    1196     logging.info('Done calling model_fn.')
>    1197 
> 
> <ipython-input-41-3124196a4b17> in _model_fn(features, labels, mode)
>      64         logits = tf.layers.dense(inputs=second_layer, units=3, activation=None)
>      65         predictions = tf.argmax(logits, 1)
> ---> 66         labels = tf.cast(labels, tf.int64)
>      67         print (labels.shape,logits.shape,predictions.shape)
>      68 
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py in cast(x, dtype, name)
>     673       # allows some conversions that cast() can't do, e.g. casting numbers to
>     674       # strings.
> --> 675       x = ops.convert_to_tensor(x, name="x")
>     676       if x.dtype.base_dtype != base_type:
>     677         x = gen_math_ops.cast(x, base_type, name=name)
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, preferred_dtype)
>    1048       name=name,
>    1049       preferred_dtype=preferred_dtype,
> -> 1050       as_ref=False)
>    1051 
>    1052 
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
>    1144 
>    1145     if ret is None:
> -> 1146       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>    1147 
>    1148     if ret is NotImplemented:
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
>     227                                          as_ref=False):
>     228   _ = as_ref
> --> 229   return constant(v, dtype=dtype, name=name)
>     230 
>     231 
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
>     206   tensor_value.tensor.CopyFrom(
>     207       tensor_util.make_tensor_proto(
> --> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>     209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
>     210   const_tensor = g.create_op(
> 
> /opt/microsoft/mlserver/9.3.0/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
>     428   else:
>     429     if values is None:
> --> 430       raise ValueError("None values not supported.")
>     431     # if dtype is provided, forces numpy array to be the type
>     432     # provided if possible.
> 
> ValueError: None values not supported.
> ```

Please ignore my query. It was due to mode in predict looking out for labels. Please ignore.

**Comment by akhorlin** [comment] 2021-06-09 13:36
Closing since Keras is the new preferred way of exporting and importing models.

**Closed by akhorlin** 2021-06-09 13:36 UTC
Labels: hub, stat:awaiting tensorflower, type:enhancement
