### ISSUE TITLE
ELMO doesn't work

### ISSUE THREAD

**Issue by fairy-of-9** [tensorflow/hub#385] opened 2019-10-15 10:06 UTC
Hi,

I have a problem using elmo.
`elmo = hub.Module("https://tfhub.dev/google/elmo/2")` doesn't work...
Is there a problem with the server?

I tired it with
```
tensorflow               1.14.0
tensorflow-hub           0.6.0
```

**Comment by gowthamkpr** [comment] 2019-10-15 17:43
@fairy-of-9 Was not able to reproduce your issue in google colab. Heres the github [gist](https://colab.sandbox.google.com/gist/gowthamkpr/eb5ff78c4d9f9129f0ddab2abdc4fbe0/untitled192.ipynb). There might be something thats hindering on your side.

**Comment by maximneumann** [comment] 2019-10-21 13:21
Confirming that elmo module works as expected with tf 1.14 and hub 0.6.

Example:
```
import tensorflow as tf
import tensorflow_hub as hub
elmo = hub.Module("https://tfhub.dev/google/elmo/2")
embeddings = elmo(
    ["the cat is on the mat", "dogs are in the fog"], signature="default", as_dict=True)["elmo"]
with tf.train.MonitoredSession() as sess:
  out = sess.run([embeddings])
```

Closing for now. If there any issues, please feel free to reopen and to provide more details on the running code and the error message.

**Closed** 2019-10-21 16:15 UTC
Labels: hub, stat:awaiting response, type:support

**Comment by mjj1094** [comment] 2020-06-19 07:21
@fairy-of-9 Have you resolved this issue? I got the same error.
