### ISSUE TITLE
Loading BERT TF2 model and accessing output layers

### ISSUE THREAD

**Issue by nouellette** [tensorflow/hub#584] opened 2020-05-15 20:21 UTC
Hello,

I'm trying to look at the output layers of BERT to see for myself which layer or layers is currently being used (when using default BERT as you'll see from code below). And then try different layers to see if i get better results for my application.

I did some searches on google to find the answer but the only thing I could find that had real code on the matter was in a video as shown below.
https://youtu.be/_eSGWNqKeeY @31:40

Here is the example code I'm working with and the TODOs is what I am trying to figure out.

```
# Using python 3.6
from absl import logging # 0.9.0 

import tensorflow as tf # 2.2.0
import tensorflow_hub as hub # 0.8.0
import tensorflow_text # 2.2.0

model = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")
vector = model('some text here to get embeddings')
# TODO: Get the output layers
# TODO: Find matching output layers to see which one matches the print statement below
print(vector)
```

I did read the documentation on tensorflow hub methods to see if I could get access but the documentation spelling out what is available seems lite on details:
https://www.tensorflow.org/hub/api_docs/python/hub/load

> .variables: a list of variables from the loaded object;
.signatures: a dict of TF2 ConcreteFunctions, keyed by signature names, that take tensor kwargs and return a tensor dict. However, the information imported by hub.Module into the collections of a tf.Graph is lost (e.g., regularization losses and update ops).

I thought the .variables was the answer because it contains a property call layers but the array is empty.

Any clarity on how to do this would be appreciated.

-Neil

**Comment by gowthamkpr** [comment] 2020-05-18 21:49
@nouellette Did you take a look at the implementation of bert in the models repo [here](https://github.com/tensorflow/models/tree/master/official/nlp/bert)?

**Comment by nouellette** [comment] 2020-05-19 00:15
@gowthamkpr I have and it's not clear how I would access the output layers. Is there a particular area you're referencing?

Also, I don't see how I would access the layers from the model loaded through tensorflow hub. Is there any code you could reference or maybe what api call to make in order to do this?

Thanks for the reply

**Comment by nouellette** [comment] 2020-05-27 00:58
Has anyone been able to take a look at this?

**Comment by nouellette** [comment] 2020-05-29 15:55
@gowthamkpr Do you think anyone will look at this or is this a lost cause?

**Comment by j-grimstad** [comment] 2020-05-29 16:07
Hi @nouellette, I believe this is a duplicate of https://github.com/tensorflow/hub/issues/465 -- unfortunately, accessing output layers of BERT isn't supported. Please reopen if I misunderstood.

**Closed by j-grimstad** 2020-05-29 16:07 UTC
Labels: stat:awaiting tensorflower, subtype:text-embedding, type:support
