### ISSUE TITLE
hub can't import

### ISSUE THREAD

**Issue by ddk1246** [tensorflow/hub#289] opened 2019-05-05 08:30 UTC
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

**Comment by rmothukuru** [comment] 2019-05-06 06:32
@ddk1246 ,
Can you please provide the code which has caused this Error. Also, can you please provide the below mentioned details.

OS : 
Python Version : 
Tensorflow Version :
TF Hub Version : 
Environment which you have run the code (Colab, Jupyter, etc) :

**Comment by ddk1246** [comment] 2019-05-06 14:56
from __future__ import absolute_import, division, print_function, unicode_literals
import matplotlib.pylab as plt
import tensorflow as tf
import tensorflow_hub as hub

error：
Traceback (most recent call last):
  File "D:/cpp/Py zk/TensorFlow2/003.py", line 4, in <module>
    import tensorflow_hub as hub
  File "D:\Python3.7.1\lib\site-packages\tensorflow_hub\__init__.py", line 30, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "D:\Python3.7.1\lib\site-packages\tensorflow_hub\estimator.py", line 63, in <module>
    class LatestModuleExporter(tf_v1.estimator.Exporter):
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

OS :Windows10
Python Version :3.7.3
Tensorflow Version :2.0
TF Hub Version :0.40
Environment which you have run the code (Colab, Jupyter, etc) :pycharm

I am green hands，thanks.

**Comment by rmothukuru** [comment] 2019-05-07 05:26
#276 This problem was addressed in Issue 276. Can you please check that issue and confirm if you are still getting the error.

**Comment by samiratzn** [comment] 2019-05-07 07:36
I get this error when importing the hub: 
please help!

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_hub\tf_v1.py in <module>
     28 try:
---> 29   from tensorflow.compat.v1 import *  # pylint: disable=wildcard-import
     30   # The previous line also gets us tensorflow.compat.v1.estimator.

ModuleNotFoundError: No module named 'tensorflow.compat.v1'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-14-5c017171c13e> in <module>
----> 1 import tensorflow_hub as hub

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_hub\__init__.py in <module>
     28 # error message is thrown instead of an obscure error of missing
     29 # symbols at executing the imports.
---> 30 from tensorflow_hub.estimator import LatestModuleExporter
     31 from tensorflow_hub.estimator import register_module_for_export
     32 from tensorflow_hub.feature_column import image_embedding_column

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_hub\estimator.py in <module>
     23 from absl import logging
     24 import tensorflow as tf
---> 25 from tensorflow_hub import tf_utils
     26 from tensorflow_hub import tf_v1
     27 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_hub\tf_utils.py in <module>
     26 import tensorflow as tf
     27 
---> 28 from tensorflow_hub import tf_v1
     29 
     30 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_hub\tf_v1.py in <module>
     31   # Be sure not to import from tensorflow_estimator without version selection.
     32 except ImportError:
---> 33   from tensorflow import add_to_collection
     34   from tensorflow import app
     35   from tensorflow import assign

ImportError: cannot import name 'add_to_collection'

**Comment by sveah** [comment] 2019-05-10 08:57
I also get this error on Mac OS Mojave 10.14.3 (18D109) with TensorFlow Version 2.0alpha0 both with Python 3.6 and 3.7. I also run the code on PyCharm with venv and TH Hub 0.40. I am green hands and not sure if issue 276 fits to my problem. 
Also when I use TF Version 1.13.1 and some sample code from the website:
`import tensorflow as tf
import tensorflow_hub as hub

tf.enable_eager_execution()

module_url = "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1"

embed = hub.Module(module_url)
embeddings = embed(["A long sentence.", "single-word",
                    "http://example.com"])
`
Then I get the following error: 
WARNING: Logging before flag parsing goes to stderr.
W0510 10:32:10.425271 4466730432 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14
Traceback (most recent call last):
  File "/Users/svea/PycharmProjects/untitled/test.py", line 8, in <module>
    embed = hub.Module(module_url)
  File "/Users/svea/PycharmProjects/untitled/venv/lib/python3.6/site-packages/tensorflow_hub/module.py", line 147, in __init__
    self._spec = as_module_spec(spec)
  File "/Users/svea/PycharmProjects/untitled/venv/lib/python3.6/site-packages/tensorflow_hub/module.py", line 36, in as_module_spec
    return load_module_spec(spec)
  File "/Users/svea/PycharmProjects/untitled/venv/lib/python3.6/site-packages/tensorflow_hub/module.py", line 61, in load_module_spec
    return registry.loader(path)
  File "/Users/svea/PycharmProjects/untitled/venv/lib/python3.6/site-packages/tensorflow_hub/registry.py", line 45, in __call__
    self._name, args, kwargs))
RuntimeError: Missing implementation that supports: loader(*('/var/folders/9n/29_gng6j51scpt88szs3bf980000gn/T/tfhub_modules/479660ef4c9d0ccd3931ea936612ee24368e86d3',), **{})

I did nothing but following the TF Installation Instructions and copy some code. How can there be such an error? Also I would prefer TF version 1.13.1 is this not possible?

**Comment by rmothukuru** [comment] 2019-05-10 09:50
@akhorlin ,
Can you PTAL

**Comment by ddk1246** [comment] 2019-05-10 10:28
it can operate in version 3.6,rather than 3.7

**Comment by little7Li** [comment] 2019-07-12 10:46
when i import tensorflow_hub the same problem happened to me.
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'
----
OS :win10
Python Version :3.6.3
Tensorflow Version :1.14.0
TF Hub Version :0.5.0
Environment which you have run the code (Colab, Jupyter, etc) :Jupyter
---
should change tensorflow version to 2.0?

**Comment by WaterMr** [comment] 2019-07-26 02:43
when i run the script "https://github.com/tensorflow/hub/raw/master/examples/image_retraining/retrain.py"
I encounter with  the problem which describes as """
Traceback (most recent call last):
  File "retrain.py", line 132, in <module>
    import tensorflow_hub as hub
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 30, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_hub/estimator.py", line 63, in <module>
    class LatestModuleExporter(tf_v1.estimator.Exporter):
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'
"""

I installed all the packages through pip
my environment is as bellow:
os: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)  version:10.14.5
Python 3.6.8

pip list:
absl-py              0.7.1               
appnope              0.1.0               
astor                0.8.0               
attrs                19.1.0              
autopep8             1.4.4               
backcall             0.1.0               
bleach               3.1.0               
cycler               0.10.0              
decorator            4.4.0               
defusedxml           0.6.0               
entrypoints          0.3                 
gast                 0.2.2               
google-pasta         0.1.7               
grpcio               1.21.1              
h5py                 2.9.0               
ipykernel            5.1.1               
ipython              7.5.0               
ipython-genutils     0.2.0               
ipywidgets           7.4.2               
jedi                 0.13.3              
Jinja2               2.10.1              
jsonschema           3.0.1               
jupyter              1.0.0               
jupyter-client       5.2.4               
jupyter-console      6.0.0               
jupyter-core         4.4.0               
Keras-Applications   1.0.8               
Keras-Preprocessing  1.1.0               
kiwisolver           1.1.0               
Markdown             3.1.1               
MarkupSafe           1.1.1               
matplotlib           3.1.0               
mistune              0.8.4               
mock                 3.0.5               
monitoring           0.9.12              
mpmath               1.1.0               
nbconvert            5.5.0               
nbformat             4.4.0               
nose                 1.3.7               
notebook             5.7.8               
numpy                1.16.4              
pandas               0.24.2              
pandocfilters        1.4.2               
parso                0.4.0               
pexpect              4.7.0               
pickleshare          0.7.5               
Pillow               6.0.0               
pip                  19.1.1              
prometheus-client    0.7.0               
prompt-toolkit       2.0.9               
protobuf             3.8.0               
ptyprocess           0.6.0               
pycodestyle          2.5.0               
Pygments             2.4.2               
pyparsing            2.4.0               
pyrsistent           0.15.2              
python-dateutil      2.8.0               
pytz                 2019.1              
PyYAML               5.1                 
pyzmq                18.0.1              
qtconsole            4.5.1               
scipy                1.3.0               
Send2Trash           1.5.0               
setuptools           41.0.1              
six                  1.12.0              
sympy                1.4                 
tb-nightly           1.14.0a20190612     
tensorboard          1.13.1              
tensorflow           1.13.1              
tensorflow-estimator 1.13.0              
tensorflow-hub       0.4.0               
termcolor            1.1.0               
terminado            0.8.2               
testpath             0.4.2               
tf-estimator-nightly 1.14.0.dev2019061201
tornado              6.0.2               
traitlets            4.3.2               
wcwidth              0.1.7               
webencodings         0.5.1               
Werkzeug             0.15.4              
wheel                0.33.4              
widgetsnbextension   3.4.2               
wrapt                1.11.1

any help thanks very much

**Comment by nayyeraafaq** [comment] 2019-07-30 06:25
after this command it should work. 
pip install "tf-nightly"

**Comment by cristine1212** [comment] 2019-10-23 20:56
> after this command it should work.
> pip install "tf-nightly"

how?

**Comment by andresusanopinto** [comment] 2019-11-01 10:11
tf-nightly package was broken at some point in that it did not included the "tf.compat.v1.estimator" symbol. I think that was has been long fixed.

**Closed by andresusanopinto** 2019-11-01 10:11 UTC
Labels: hub, stat:awaiting tensorflower, type:support

**Comment by jPPuetz** [comment] 2020-02-03 11:26
Hi,
wanted to notice that I'm having this issue again with Tensorflow Hub (normal not nightly).

Using venv and freshly installed tf and tf-hub, also tried tf-nightly but this didn't change anything:
```
OS : Windows 10 Pro 64bit
Python Version : Python 3.7.0
tensorflow 2.1.0
tensorflow-estimator 2.1.0
tensorflow-hub 0.7.0
Environment which you have run the code (Colab, Jupyter, etc) : Jupyter and PyCharm
```

Code used for testing:
```
import tensorflow_hub as hub
embed = hub.load("./USE/universal-sentence-encoder-large.tar.gz")
embeddings = embed([
    "The quick brown fox jumps over the lazy dog.",
    "I am a sentence for which I would like to get its embedding"])
print(embeddings)
```

Stack trace:
```
Traceback (most recent call last):
  File "\env\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-bb9e497df10e>", line 1, in <module>
    import tensorflow_hub as hub
  File "\env\lib\site-packages\tensorflow_hub\__init__.py", line 29, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "\env\lib\site-packages\tensorflow_hub\estimator.py", line 64, in <module>
    class LatestModuleExporter(tf_v1.estimator.Exporter):
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'
```

**Comment by muhammadmehranbinazam** [comment] 2021-12-14 16:57
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ae25cc1fd345> in <module>
      1 import tensorflow as tf
----> 2 import tensorflow_hub as hub

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_hub\__init__.py in <module>
     86 
     87 
---> 88 from tensorflow_hub.estimator import LatestModuleExporter
     89 from tensorflow_hub.estimator import register_module_for_export
     90 from tensorflow_hub.feature_column import image_embedding_column

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_hub\estimator.py in <module>
     59 
     60 
---> 61 class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
     62   """Regularly exports registered modules into timestamped directories.
     63 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     60 
     61   def __getattr__(self, item):
---> 62     module = self._load()
     63     return getattr(module, item)
     64 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     43     """Load the module and insert it into the parent's globals."""
     44     # Import the target module and insert it into the parent's namespace
---> 45     module = importlib.import_module(self.__name__)
     46     self._parent_module_globals[self._local_name] = module
     47 

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1 import estimator
     11 
     12 del _print_function

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1.estimator import experimental
     11 from tensorflow_estimator._api.v1.estimator import export
     12 from tensorflow_estimator._api.v1.estimator import inputs

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
     11 from tensorflow_estimator.python.estimator.canned.kmeans import KMeansClustering as KMeans
     12 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py in <module>
     27 from tensorflow_estimator.python.estimator import estimator
     28 from tensorflow_estimator.python.estimator.canned import head as head_lib
---> 29 from tensorflow_estimator.python.estimator.canned import optimizers
     30 from tensorflow_estimator.python.estimator.head import head_utils
     31 from tensorflow_estimator.python.estimator.head import regression_head

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\canned\optimizers.py in <module>
     32 
     33 _OPTIMIZER_CLS_NAMES_V2 = {
---> 34     'Adagrad': tf.keras.optimizers.Adagrad,
     35     'Adam': tf.keras.optimizers.Adam,
     36     'Ftrl': tf.keras.optimizers.Ftrl,

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     60 
     61   def __getattr__(self, item):
---> 62     module = self._load()
     63     return getattr(module, item)
     64 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     43     """Load the module and insert it into the parent's globals."""
     44     # Import the target module and insert it into the parent's namespace
---> 45     module = importlib.import_module(self.__name__)
     46     self._parent_module_globals[self._local_name] = module
     47 

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
     23 
     24 # See b/110718070#comment18 for more details about this import.
---> 25 from keras import models
     26 
     27 from keras.engine.input_layer import Input

C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py in <module>
     17 
     18 import tensorflow.compat.v2 as tf
---> 19 from keras import backend
     20 from keras import metrics as metrics_module
     21 from keras import optimizer_v1

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
     23 from distutils.version import StrictVersion
     24 
---> 25 from ..utils.generic_utils import transpose_shape
     26 
     27 py_all = all

ImportError: cannot import name 'transpose_shape' from 'keras.utils.generic_utils' (C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\generic_utils.py)
