### ISSUE TITLE
AttributeError: module 'tensorflow_hub' has no attribute 'KerasLayer'

### ISSUE THREAD

**Issue by bilafish** [tensorflow/hub#255] opened 2019-03-17 15:28 UTC
Hi, I encountered this error 
> AttributeError: module 'tensorflow_hub' has no attribute 'KerasLayer'

 when trying to build the model.
`model = tf.keras.Sequential([
    hub.KerasLayer(MODULE_HANDLE, output_shape=[FV_SIZE],
                   trainable=do_fine_tuning),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(train_generator.num_classes, activation='softmax',
                          kernel_regularizer=tf.keras.regularizers.l2(0.0001))
])`

I'm on TensorFlow v1.9 and TensorFlow Hub v0.3.0

**Comment by vbardiovskyg** [comment] 2019-03-19 11:17
Hi Jason, hub.KerasLayer works with TF2 pre releases, so:

`pip install tf-nightly-2.0-preview --quiet`
or
`pip install tensorflow==2.0.0-alpha`
or a pre-release candidate for GPU
`pip install -U --pre tensorflow-gpu`

**Comment by hgadig** [comment] 2019-03-29 17:41
Closing as it is in "awaiting response" status for more than 7 days. Feel free to add your comments and we will reopen.

**Comment by Belginwls** [comment] 2019-04-23 04:21
thanks alot @vbardiovskyg  pip install tensorflow==2.0.0-alpha it work to me.now am have the another one issue i cant save the model it shows an error 

` **Unable to create link (name already exists) tensorflow alpha version**`

please help!!

**Comment by vbardiovskyg** [comment] 2019-04-23 08:12
Looks like some sort of Keras & SavedModel integration issue, judging by related TF issues:
https://github.com/tensorflow/tensorflow/issues/26835
https://github.com/tensorflow/tensorflow/issues/27688
https://github.com/tensorflow/tensorflow/issues/27909

Maybe @arnoegw would have already seen this before?

**Comment by rmothukuru** [comment] 2019-04-30 13:37
@arnoegw ,
Can you PTAL.

**Comment by arnoegw** [comment] 2019-05-03 15:56
@Belginwls: That's really a separate issue now.

@vbardiovskyg: Thanks for digging up those similar errors, I think some have a common root cause.

I've filed issue https://github.com/tensorflow/hub/issues/287 to track investigating and fixing hub.KerasLayer. Let's unify the discussion there.

**Closed by arnoegw** 2019-05-03 15:56 UTC
Labels: hub, stat:awaiting tensorflower, type:support
