### ISSUE TITLE
Tensorflow gpu isn't detected by python in IDLE

### ISSUE THREAD

**Issue by happyface662233** [tensorflow/hub#656] opened 2020-08-15 22:20 UTC
My problem is that I have tried to set up tensorflow GPU multiple times for my GTX 1050ti. I have installed all the latest drivers, and followed all the steps at https://www.tensorflow.org/install/gpu my path is all set up right (I believe) and I have installed tensorflow 1.15 gpu version as seen on the website too. pip install tensorflow-gpu==1.15. I have cuDNN 7.4 and CUDA toolkit 10.0. Any help would be greatly greatly appreciated. If you need anymore info please ask. Thanks for the help

**Comment by rmothukuru** [comment] 2020-08-17 06:03
@happyface662233,
As the issue is related to Tensorflow and not related to TF Hub, please raise the Issue in [Tensorflow Github Repository](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by rmothukuru** [comment] 2020-08-31 04:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-08-31 04:56 UTC
Labels: stat:awaiting response, type:build/install
