### ISSUE TITLE
tf.keras.models.load_model fails with bert_en_uncased_preprocess

### ISSUE THREAD

**Issue by thzheng** [tensorflow/hub#750] opened 2021-03-18 22:58 UTC
With the **general usage** described in https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3
bert_en_uncased_preprocess model fails to reload. 

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("inputs:0", shape=(None,), dtype=int32), row_splits=Tensor("inputs_2:0", shape=(None,), dtype=int64)), row_splits=Tensor("inputs_1:0", shape=(None,), dtype=int64))
    * False
  Keyword arguments: {}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (2 total):
    * [RaggedTensorSpec(TensorShape([None, None, None]), tf.int32, 2, tf.int64)]
    * False
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * [RaggedTensorSpec(TensorShape([None, None, None]), tf.int32, 2, tf.int64)]
    * True
  Keyword arguments: {}

Here is an example in colab to reproduce:
https://colab.research.google.com/drive/1LeiAGgycsTxsKWeKIm6Hs8UwMFA4O-VP?usp=sharing
This issue only happens to general usage, the basic usage is fine.

load_weights workaround mentioned in https://github.com/tensorflow/hub/issues/747 works but it only restore the weight and you need to reconstruct a model. 
And the tf.saved_model.load doesn’t return a keras model and lacks keras apis

**Comment by hanneshapke** [comment] 2021-03-19 00:48
The workaround via `hub.KerasLayer` as suggested by @kempy worked for me. No loading of the weights only is needed.
https://github.com/tensorflow/hub/issues/747

**Comment by arghyaganguly** [comment] 2021-03-19 06:20
@thzheng,please confirm whether to close this as duplicate of #747.Thanks.

**Comment by thzheng** [comment] 2021-03-19 18:48
> @thzheng,please confirm whether to close this as duplicate of #747.Thanks.

Checked the workarounds in #747 , but it still does not solve all the issues. E.g. TF serving still fails to load the model and cannot use these workarounds.

**Comment by hanneshapke** [comment] 2021-03-19 21:42
@thzheng I am using the workaround in production (via TFServing, version 2.4.0) now. In our particular case, it reduced the model latency by 3/4. Can you share your export code so I can confirm the setup (sorry, I can't share my code)?
Btw, which TFServing version are you running? Earlier versions (I think 2.2.0 and earlier) didn't support all TF-text goodies.

**Comment by arghyaganguly** [comment] 2021-03-22 10:34
@thzheng , please provide a colab link with the code snippet to reproduce the same along with the TFServing version you are using.If this is a  TFServing specific issue(inadequacy in version), we might need to raise this in [link](https://github.com/tensorflow/serving/issues) .
Thanks.

**Comment by catsharkdigital** [comment] 2021-03-23 18:43
> > @thzheng,please confirm whether to close this as duplicate of #747.Thanks.
> 
> Checked the workarounds in #747 , but it still does not solve all the issues. E.g. TF serving still fails to load the model and cannot use these workarounds.

This is where I am at with this issue as well

**Comment by hanneshapke** [comment] 2021-03-23 23:40
@catsharkdigital @thzheng Can anyone please share information regarding the TFServing version you are using, and how you export the model? I can confirm that I am using the workaround in a variety of production models now. Those models are being served with TFServing. Unfortunately, I can't share any code from my side.

**Comment by arghyaganguly** [comment] 2021-04-12 06:36
Closing this due to inactivity.Please feel free to reopen if it is still  a hub specific issue or create a new issue in TensorFlow serving repo.

**Closed by arghyaganguly** 2021-04-12 06:36 UTC
Labels: hub, stat:awaiting response, subtype:text-embedding, type:docs, type:support
