### ISSUE TITLE
Why USE base model is larger than USE large model?

### ISSUE THREAD

**Issue by maziyarpanahi** [tensorflow/hub#460] opened 2019-12-26 11:38 UTC
Hi,

I've noticed the https://tfhub.dev/google/universal-sentence-encoder/2  model is larger than https://tfhub.dev/google/universal-sentence-encoder-large/3 model.

When you see `large` in a model's name you assume the other one without the size being mention is base/small(er) than the large model. Is it possible these two models are reversed? Like when we are downloading the normal USE we are downloading the large version and vice versa?

The large model is over 520MB and the base (without size mentioned) is over 900MB.

Thanks,

**Comment by gowthamkpr** [comment] 2019-12-26 22:51
@maziyarpanahi The main difference in sizes is due to the difference in architectures used in them. https://tfhub.dev/google/universal-sentence-encoder/2 uses deep averaging network which is mainly used when you are looking for efficient inference with slightly reduced accuracy while the other https://tfhub.dev/google/universal-sentence-encoder-large/3  uses transformer architecture which  targets high accuracy at the cost of greater model complexity. 

For more detailed information you can read the following paper [here](https://arxiv.org/pdf/1803.11175.pdf). Thanks!

**Comment by gowthamkpr** [comment] 2020-01-02 19:00
Closing this issue as it is not a bug and is resolved. Please add additional comments and we can open this issue again. Thanks!

**Closed by gowthamkpr** 2020-01-02 19:00 UTC
Labels: stat:awaiting response, type:support
