### ISSUE TITLE
hub.KerasLayer error when run_functions_eagerly = True

### ISSUE THREAD

**Issue by JustASquid** [tensorflow/hub#666] opened 2020-09-07 05:49 UTC
In Tensorflow 2.3 (Windows, GPU) the following code results in an error, only when `run_functions_eagerly` is `True`:

```
tf.config.run_functions_eagerly(True)

image_input = keras.Input(shape=(224, 224, 3), name="image")
x = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4")(image_input)
```

The error is:

```
    ValueError: Could not find matching function to call loaded from the SavedModel. Got:
      Positional arguments (1 total):
        * Tensor("image:0", shape=(None, 224, 224, 3), dtype=float32)
      Keyword arguments: {'training': False}
    
    Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (4 total):
        * TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        * False
        * False
        * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (4 total):
        * TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        * True
        * True
        * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
      Keyword arguments: {}
    
    Option 3:
      Positional arguments (4 total):
        * TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        * False
        * True
        * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
      Keyword arguments: {}
    
    Option 4:
      Positional arguments (4 total):
        * TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        * True
        * False
        * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
      Keyword arguments: {}


Process finished with exit code -1
```

**Comment by rmothukuru** [comment] 2020-09-08 11:14
Could reproduce the error. Please find the [Colab Gist](https://colab.research.google.com/gist/rmothukuru/2a90b8fda199a0e673b5f5721ec7f739/gh_hub_666.ipynb). Thanks!

**Comment by arnoegw** [comment] 2020-09-11 17:38
This is a problem with the way a tf.function restored from a SavedModel gets its arguments matched if `tf.config.run_functions_eagerly(True)` has been set, independent of the SavedModel at hand or the operating system being used. The expected behavior is to execute that tf.function normally (that is, non-eagerly, because its Python code is no longer available) instead of failing. This needs to be fixed inside TensorFlow, and we have raised it with them.

Until this gets fixed in a future TensorFlow release, the only advice for users of SavedModels from TF Hub is to not use this debugging facility. Sorry.

**Comment by JustASquid** [comment] 2020-09-11 23:53
Thanks @arnoegw.
Do you have a link to the issue on the main Tensorflow repository so I can follow?
Also, can you suggest any workarounds?
Happy for you to close the issue if not.

**Comment by arnoegw** [comment] 2020-09-14 08:26
Hi @JustASquid, I'm not aware of a better workaround than having `run_functions_eagerly` set to `False` for the part of your code that handles SavedModels (possibly indirectly via `hub.KerasLayer`.

Our report to TensorFlow team is tracked outside GitHub (so I can't link to it), but I'll keep TF Hub users posted here.

**Comment by andrew-alm** [comment] 2020-11-26 22:48
I've been playing with this issue for a bit, and setting `run_functions_eagerly` to `False` hasn't worked. Even on the most basic example below, the error is still there.

`tensorflow==2.31` , `tensorflow-hub==0.10.0`

```tf.config.run_functions_eagerly(False)

model = hub.KerasLayer('https://tfhub.dev/google/imagenet/inception_v3/classification/4', run_functions_eagerly)

image = np.asanyarray(Image.open('photos/2007_000033.jpg'))
model(image)```

**Comment by arnoegw** [comment] 2020-12-11 15:58
That's correct, our report to the TensorFlow team has not been resolved yet.

**Comment by arnoegw** [comment] 2021-02-09 07:43
@dellis23 has fixed this in commit https://github.com/tensorflow/tensorflow/commit/a02ad9725c47a7b24d96ffe09e1dbcd1065a4a1f which is already available in the latest tf-nightly pip packages, and will become part of TF 2.5.0.

No update is needed for the tensorflow_hub library or the models on TF Hub.

**Closed by arnoegw** 2021-02-09 07:43 UTC
Labels: stat:awaiting tensorflower, subtype:image-feature-vector, type:bug
