### ISSUE TITLE
USE Large 4 fails to load in collab

### ISSUE THREAD

**Issue by vprelovac** [tensorflow/hub#405] opened 2019-11-08 23:28 UTC
Using Google Collab with Tf2.0

```
url = "https://tfhub.dev/google/universal-sentence-encoder-large/4"
embed = hub.Module(url)
```

results in:

```
/usr/local/lib/python3.6/dist-packages/tensorflow_hub/registry.py in __call__(self, *args, **kwargs)
     43     raise RuntimeError(
     44         "Missing implementation that supports: %s(*%r, **%r)" % (
---> 45             self._name, args, kwargs))
     46 
     47 

RuntimeError: Missing implementation that supports: loader(*('/tmp/tfhub_modules/f4ea2eb4a9fd72946209ef45271146fae070fb29',), **{})
```

https://tfhub.dev/google/universal-sentence-encoder-large/3 loads without problems.

**Comment by brenting** [comment] 2019-11-11 08:34
Try:
```python
url = "https://tfhub.dev/google/universal-sentence-encoder-large/4"
embed = hub.load(url)
```

hub.load is replacing hub.Module in TF2.0:
https://www.tensorflow.org/hub/tf2_saved_model

**Comment by vbardiovskyg** [comment] 2019-11-11 08:36
Thanks Bram! Yes, I will update the USE docs soon too. There are several new USE models republished with TF2 compatibility. We will try to make that more obvious.

**Comment by jdeason23** [comment] 2019-11-13 01:38
Same issue here.  I am using

url = "https://tfhub.dev/google/universal-sentence-encoder-large/4"
embed = hub.load(url)

Error:
--------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    426         results = c_api.TF_GraphImportGraphDefWithResults(
--> 427             graph._c_graph, serialized, options)  # pylint: disable=protected-access
    428         results = c_api_util.ScopedTFImportGraphDefResults(results)

InvalidArgumentError: NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, ..., DT_QINT8, DT_QINT32, DT_STRING, DT_BOOL, DT_COMPLEX128]; is_commutative=true>; NodeDef: {{node Equal}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-18-54aa9a7e52b3> in <module>()
      4 #embed = hub.load(module_url)
      5 url = "https://tfhub.dev/google/universal-sentence-encoder-large/4"
----> 6 embed = hub.load(url)
      7 # embed = hub.Module(module_url)
      8 # hub_layer = hub.KerasLayer(module_url, input_shape=[],

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_hub/module_v2.py in load(handle, tags)
     93   if tags is None and is_hub_module_v1:
     94       tags = []
---> 95   obj = tf_v1.saved_model.load_v2(module_path, tags=tags)
     96   obj._is_hub_module_v1 = is_hub_module_v1  # pylint: disable=protected-access
     97   return obj

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in load(export_dir, tags)
    406     ValueError: If `tags` don't match a MetaGraph in the SavedModel.
    407   """
--> 408   return load_internal(export_dir, tags)
    409 
    410 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, loader_cls)
    430       loader = loader_cls(object_graph_proto,
    431                           saved_model_proto,
--> 432                           export_dir)
    433       root = loader.get(0)
    434     root.tensorflow_version = meta_graph_def.meta_info_def.tensorflow_version

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py in __init__(self, object_graph_proto, saved_model_proto, export_dir)
     55     self._concrete_functions = (
     56         function_deserialization.load_function_def_library(
---> 57             meta_graph.graph_def.library))
     58     self._load_all()
     59     # TODO(b/124045874): There are limitations with functions whose captures

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py in load_function_def_library(library)
    294     copy = _fix_fdef(fdef, functions, load_shared_name_suffix)
    295 
--> 296     func_graph = function_def_lib.function_def_to_graph(copy)
    297     for dep in _list_function_deps(fdef):
    298       functions[dep].add_to_graph(func_graph)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py in function_def_to_graph(fdef, input_shapes)
     60   with func_graph.as_default():
     61     # Add all function nodes to the graph.
---> 62     importer.import_graph_def(graph_def, name="")
     63 
     64     # Initialize fields specific to FuncGraph.

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    429       except errors.InvalidArgumentError as e:
    430         # Convert to ValueError for backwards compatibility.
--> 431         raise ValueError(str(e))
    432 
    433     # Create _DefinedFunctions for any imported functions.

ValueError: NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, ..., DT_QINT8, DT_QINT32, DT_STRING, DT_BOOL, DT_COMPLEX128]; is_commutative=true>; NodeDef: {{node Equal}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

**Comment by vbardiovskyg** [comment] 2019-11-13 15:17
Hi @jdeason23, I can't reproduce this in the public Google colab, could you please share your tensorflow and tensorflow_hub versions?

**Comment by jdeason23** [comment] 2019-11-13 16:19
Sorry, it works in Colab.  I was originally running in a Jupyter Notebook on AWS SageMaker.  Tensorflow installed on SageMaker notebook is 2.0.0-beta1 and Hub is 0.7.0.  Maybe the beta1 is the problem.

**Comment by rmothukuru** [comment] 2019-11-21 04:17
@vprelovac,
Can you please let us know if your problem is resolved? Else, as per @vbardiovskyg's comments, can you please share tensorflow and tensorflow_hub versions? Thanks!

**Comment by jdeason23** [comment] 2019-11-21 13:50
You can mark this as resolved.  It works in SageMaker/Jupyter (and Collab) with TF 2.0.0 and TF Hub 0.7.0.  Must have been an issue with the beta.  Thanks

**Comment by rmothukuru** [comment] 2019-11-21 14:12
Closing the issue as it has been resolved.

**Closed by rmothukuru** 2019-11-21 14:12 UTC
Labels: stat:awaiting response, subtype:text-embedding, type:docs
