### ISSUE TITLE
Running on my local machine

### ISSUE THREAD

**Issue by GinaJemy** [tensorflow/hub#436] opened 2019-12-02 19:54 UTC
Traceback (most recent call last):
  File "tf_hub.py", line 152, in <module>
    run_detector(detector, downloaded_image_path)
  File "tf_hub.py", line 141, in run_detector
    result = {key:value.numpy() for key,value in result.items()}
  File "tf_hub.py", line 141, in <dictcomp>
    result = {key:value.numpy() for key,value in result.items()}
AttributeError: 'Tensor' object has no attribute 'numpy'

After downloading the image it stops with this error.
I have tensorflow 1.14 and python3

**Comment by rmothukuru** [comment] 2019-12-03 03:37
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2019-12-19 06:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-12-19 06:17 UTC
Labels: stat:awaiting response, type:support
