### ISSUE TITLE
How to get model predictions on all classes after applying Transfer Learning in TF2.0?

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/hub#328] opened 2019-07-04 15:26 UTC
I have been following [transfer learning with TFHub](https://www.tensorflow.org/beta/tutorials/images/hub_with_keras) to implement transfer learning in my model for text classification. In the example, I do not understand how to get probabilities for all the classes (1000 classes before + 5 classes after implementing transfer learning). At the end of the tutorial, they only show predictions on the 5 classes on which the model was re-trained, but I want to have probabilities also on the 1000 classes. I can not find any documentation or explanation on how to achieve this. If anyone has any ideas or some useful links, please feel free to share. THANK YOU!
This was my main question.

About model, where I want to implement this idea of transfer learning.
I have a text dataset of 8000 classes, since the data size is too big so it can not be loaded into the RAM of my machine. So I want to train on small-small sizes of data i.e. 4000 classes and 4000 classes. I trained my model freshly on 4000 classes first, the learned model gives me good results. Now I want to retrain the saved model on the rest 4000 classes using Transfer Learning (I am also open to any other way), but after doing a lot of google searches seems like it is impossible to retrain a model on new classes, at least in text classification. If you have read this part and have some suggestions or ideas please share them, I will be very thankful.

**Comment by rmothukuru** [comment] 2019-07-05 07:56
@rishabhsahrawat ,
You need to Save the Model without the Final Layer of the Text Classification using [tf.saved_model.save](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/saved_model/save)
Then load the previously Saved [Head Less Model]  (https://www.tensorflow.org/tutorials/images/hub_with_keras#download_the_headless_model) using [this Method](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/saved_model/load), ingest the next set of data corresponding to 4000 labels.
After that, you need to attach the [Final Layer of Text Classification](https://www.tensorflow.org/tutorials/images/hub_with_keras#attach_a_classification_head).

**Comment by rishabhsahrawat** [comment] 2019-07-05 08:19
@rmothukuru thank you very much for your answer and explanation. After following your suggested steps, attaching the final layer like [Final Layer of Text Classification](https://www.tensorflow.org/tutorials/images/hub_with_keras#attach_a_classification_head) I will still only get predictions among the next 4000 classes not 8000 classes because the last layer had 4000 output neurons. My question is still the same, I want to get the predictions from all the 8000 classes after using transfer learning.
Please let me know if I am missing something in your point. 
-Rishabh Sahrawat

**Comment by vbardiovskyg** [comment] 2019-07-05 08:46
Hi Rishabh, interesting question.

First of all, your dataset doesn't have to fit in RAM. Would your model be too big to train using 8000 classes? You can use tf.data.Dataset which will iterate over data from disk.
(https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches, https://www.tensorflow.org/beta/guide/keras/training_and_evaluation#training_evaluation_from_tfdata_datasets)

If model size is still a problem, you could in theory do this kind of training, but I am really not sure how stable it would be, i.e. training on 4000-head could significantly worsen performance on the other 4000-head. 

You could technically do this by always keeping reference to the following:
`feature_extractor_layer`,
`head1 = layers.Dense(4000, activation='softmax')`,
`head2 = layers.Dense(4000, activation='softmax')`.

Between trainings you would recompile:
```
model = tf.keras.Sequential([
  feature_extractor_layer,
  head1
])
model.compile(...)
```
Of course this won't fit into your memory, so you can use `tf.saved_model.save(feature_extractor_layer)` and `tf.saved_model.save(head1)` as described in @rmothukuru's answer.

**Comment by rishabhsahrawat** [comment] 2019-07-05 10:14
Hallo @vbardiovskyg , thank you so much for your helpful reply. Since I am new to TF, until now I had been using [train/test split function](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn-model-selection-train-test-split) from Scikit-Learn, which made my machine run out of memory if I try to use all 8000 classes. So, after looking for solutions I found I can convert my data file into TFRecords and then use the whole dataset because it speeds up the data processing. Although, to be honest I have no idea if your suggested links (TF train/test split) and the TFRecord have the same data processing speeds. 

Your second suggestion, 
>You could technically do this by always keeping reference to the following:
feature_extractor_layer,
head1 = layers.Dense(4000, activation='softmax'),
head2 = layers.Dense(4000, activation='softmax').

Do you mean I need to add these two **head1, head2** output layers in the second model(retraining model)?. Will they be connected in parallel to each other?
If not, then I think the final layer of the model will still have 4000 classes which means it will give probabilities between those last 4000 classes. 

-Rishabh Sahrawat

**Comment by vbardiovskyg** [comment] 2019-07-05 11:03
The mentioned scikit-learn function works over numpy objects in memory, so I highly recommend learning more on the tf.data.Dataset side and reading from disk. Then your problem might disappear completely.

You are right that the final model would have 4000 classes. This was just a theoretical example of how that could work technically. I would recommend getting a proper set-up instead (as mentioned above), so you can use full model with 8000 classes.

**Comment by rishabhsahrawat** [comment] 2019-07-05 11:47
Thank you, I think this makes more sense. I will try this now then.

**Comment by rmothukuru** [comment] 2019-07-08 05:07
@rishabhsahrawat ,
Can you please confirm if you have tried @vbardiovskyg's solution and if the issue is resolved, so that we can close this issue.

**Comment by rishabhsahrawat** [comment] 2019-07-08 06:53
@rmothukuru , not yet but I am working on it. It should be done soon. I will update here.

**Comment by rishabhsahrawat** [comment] 2019-07-15 07:49
@rmothukuru Hi, as suggested by @vbardiovskyg to load data using `tf.data.Dataset`, I implmented this idea and it worked well without filling up the memory. Now I have two questions regarding it-
1. Before every epoch it fills up the buffer, which is a bit time taking event. Is it a normal behaviour or can I somehow disable it after the first time it loads? I also opened an [issue](https://github.com/tensorflow/tensorflow/issues/30646).
2. How is the way different from tf.Record? Is it more better in terms of speed or something?

Thank you!
Rishabh Sahrawat

**Comment by gowtham-kp** [comment] 2019-07-31 22:11
Closing this issue as it has been answered. Thanks!

**Closed by gowtham-kp** 2019-07-31 22:11 UTC
Labels: hub, stat:awaiting response, subtype:text-embedding, type:support

**Comment by rishabhsahrawat** [comment] 2019-08-02 13:10
Although I still have unanswered questions from my last comment but OK.

**Comment by vbardiovskyg** [comment] 2019-08-02 13:25
Hi Rishabh,

sorry about this. The questions you posted are not about TensorFlow Hub, but about tf.data, so we are not in a good position to answer them.

The one you posted on TF seems reasonable.

**Comment by rishabhsahrawat** [comment] 2019-08-02 13:36
Hallo,
thank you for your clarification. I will try to ask them there.
