### ISSUE TITLE
Fine-tunning: Module variables do not change during training

### ISSUE THREAD

**Issue by PetrBo** [tensorflow/hub#269] opened 2019-04-01 12:33 UTC
Hello, 

I'm trying to apply fine-tunning on [MobileNetV2](https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/feature_vector/2) – the module is instantiated with `hub.Module(..., trainable=True, tags={"train"})`. Unfortunately only my custom final FC layer is trained during the training phase. 

I have also noticed that my _custom trainable variables_ (**do** change during the training) have `dtype=float32_ref` whereas _module trainable variables_ (**do not** change during the training) have `dtype=float32`. I don't really understand to implementation details of TensorFlow but this seems a little bit strange to me (see [Stackoverflow](https://stackoverflow.com/questions/37958706/in-tensorflow-what-is-the-difference-between-a-tensor-that-has-a-type-ending-in)).

I have even tried to create train_op using `tf.contrib.training.create_train_op()` and to take into account `tf.losses.get_regularization_loss()` as suggested in issue #24 – did not helped. The same is happened when I use [InceptionV3](https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1).

So the question is why my _custom variables_ **are** trained and module variables **are not** (even though ` trainable=True, tags={"train"}`)? Is there anything else what I need to do to do the fine-tunning or is it a bug of TensorFlow Hub?

Thanks in advance!

Version of Tensorflow: 1.12.0
Version of Tensorflow Hub: 0.3.0
OS : Ubuntu 18.04
Python Version: 3.6.7

**Comment by rmothukuru** [comment] 2019-04-05 04:36
Hello PetrBo,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2019-04-09 03:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sergeyleyko** [comment] 2019-07-29 16:39
Hi there,
I'm experiencing exactly the same issue as topic starter.. Is there any suggestion on how to resolve it?
@PetrBo have you found out the problem? Maybe something from https://github.com/tensorflow/hub/issues/24 issue can resolve it?

**Comment by PetrBo** [comment] 2019-07-29 17:09
@sergeyleyko unfortunately not. I have migrated the project I'm working on to Keras.

**Comment by sergeyleyko** [comment] 2019-07-30 11:01
@rmothukuru Hi,
I've posted the question with details about the issue onto the stackoverflow, can we reopen the issue now? https://stackoverflow.com/questions/57269598/tensorflow-hub-modules-trainable-variables-are-not-updated-during-training

**Comment by sergeyleyko** [comment] 2019-07-30 16:05
Here is the sample notebook with the problem reproduced:
https://colab.research.google.com/drive/1PKUyoQRP3othu6cu7v7N7yn8K2pjkuKP

**Comment by sergeyleyko** [comment] 2019-08-01 09:54
Okay, after deep debugging of a issue I found that the problem is in following:
just getting the variable from a global variable list and getting it's value using eval() on it is not enough: it will return some value but it is not current (at least this is what happening for the variables of imported model with dtype=resource).

To calculate current value we have to get first a value tensor using variable.value() or variable.read_value() and doing eval() for it.

This resolves the question.

@rmothukuru please close the issue.
@PetrBo FYI

**Comment by rmothukuru** [comment] 2019-08-01 10:02
@PetrBo ,
Can you please confirm if @sergeyleyko's solution worked for you as well. Thanks!

**Comment by rmothukuru** [comment] 2019-08-05 05:35
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-08-05 05:35 UTC
Labels: hub, stat:awaiting response, type:support
