### ISSUE TITLE
ALBERT model does not work with GradientTape

### ISSUE THREAD

**Issue by Enumaris** [tensorflow/hub#622] opened 2020-06-19 18:32 UTC
I'm trying to fine-tune an ALBERT model using a `tf.GradientTape()` method but I'm running into an error. The minimum code to reproduce the error would be:
```
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow import keras
import numpy as np

def get_model():
    global max_seq_length
    global batch_size
    input_word_ids = keras.layers.Input(batch_shape=(batch_size, max_seq_length, ), 
                                           dtype=tf.int32,
                                           name="input_word_ids")
    input_mask = keras.layers.Input(batch_shape=(batch_size, max_seq_length, ), 
                                       dtype=tf.int32,
                                       name="input_mask")
    segment_ids = keras.layers.Input(batch_shape=(batch_size, max_seq_length, ), 
                                        dtype=tf.int32,
                                        name="segment_ids")
    albert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/albert_en_base/1",
                                  trainable=True,
                                  name='albert_layer')
    pooled_output, sequence_output = albert_layer([input_word_ids, input_mask, segment_ids])
    output = keras.layers.Dense(2)(sequence_output)

    model = keras.Model(inputs=(input_word_ids, input_mask, segment_ids),
                        outputs=output)
    print(model.summary())
    return model


batch_size = 4
max_seq_length = 16
model = get_model()

input_ids = 5 * np.ones((4, 16), dtype=np.int32)
input_mask = np.ones((4, 16), dtype=np.int32)
segment_ids = np.zeros((4, 16), dtype=np.int32)

with tf.GradientTape(persistent=True) as tape:
    logits = model({
                  'input_word_ids' : input_ids,
                  'input_mask' : input_mask,
                  'segment_ids' : segment_ids
    })
    print(logits)
```

Running this produces the following stack trace: 
```
Traceback (most recent call last):
  File "albert_gradient_tape_test.py", line 42, in <module>
    'segment_ids' : segment_ids
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py", line 218, in call
    lambda: f(training=False))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py", line 218, in <lambda>
    lambda: f(training=False))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 438, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2362, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 241, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 72, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 99, in _call_flat
    cancellation_manager)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1697, in _call_flat
    forward_function, args_with_tangents = forward_backward.forward()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1423, in forward
    self._inference_args, self._input_tangents)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1185, in forward
    self._forward_and_backward_functions(inference_args, input_tangents))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1379, in _forward_and_backward_functions
    outputs, inference_args, input_tangents)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 882, in _build_functions_for_outputs
    output)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/ops/default_gradient.py", line 45, in shape_and_dtype
    "of a variable without handle data:\n%s" % str(t))
ValueError: Internal error: Tried to take gradients (or similar) of a variable without handle data:
Tensor("StatefulPartitionedCall:949", shape=(), dtype=resource)
```

If I execute the model without a `tf.GradientTape()` context the model runs. It looks like the `StatefulPartitionedCall:949` tensor has no "handle" but I don't know what that means. 

I'm using the following versions:
```
tensorflow-hub == 0.8.0
tensorflow == 2.1.0
python == 3.7.6
```

**Comment by rmothukuru** [comment] 2020-06-22 06:20
Could reproduce the error in Google Colab. Please find the [Github Gist](https://colab.research.google.com/gist/rmothukuru/e9a07da7ebe9d3feaebd3df532991a86/hub_622.ipynb). Thanks.

**Comment by chenGitHuber** [comment] 2020-06-22 17:11
Hi, as a workaround, could you try to remove "persistent=True"?

**Comment by Enumaris** [comment] 2020-06-22 22:10
> Hi, as a workaround, could you try to remove "persistent=True"?

It appears that removing `persistent=True` will no longer give rise to this error. However, for my use case, I require persistence of the gradient tape because I will be calling `tape.gradient()` multiple times.

**Comment by cswhjiang** [comment] 2021-03-09 02:04
> > Hi, as a workaround, could you try to remove "persistent=True"?
> 
> It appears that removing `persistent=True` will no longer give rise to this error. However, for my use case, I require persistence of the gradient tape because I will be calling `tape.gradient()` multiple times.

Is this bug still not fixed?

**Comment by chenGitHuber** [comment] 2021-03-09 05:49
I think this issue has been fixed in the latest ALBERT hub model: https://tfhub.dev/tensorflow/albert_en_base/2

@arnoegw could you please confirm?

**Comment by cswhjiang** [comment] 2021-03-09 06:11
> I think this issue has been fixed in the latest ALBERT hub model: https://tfhub.dev/tensorflow/albert_en_base/2
> 
> @arnoegw could you please confirm?

We use the Chinese model (https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip). Could you please also this one？

**Comment by ziyuwwang** [comment] 2021-03-09 08:28
> I think this issue has been fixed in the latest ALBERT hub model: https://tfhub.dev/tensorflow/albert_en_base/2
> 
> @arnoegw could you please confirm?

I tried the latest BERT hub model and still got the same error. Could you explain what causes this bug and what has been changed in the latest hub models to fix this bug?

**Comment by arnoegw** [comment] 2021-03-09 16:01
The root cause has been fixed on the master branch of tensorflow with commit https://github.com/tensorflow/tensorflow/commit/8318ab26da58de5384d3809c373785dce27303d5

To get the fix,
  * the user needs to run a recent tf-nightly, or tensorflow 2.5.0 when it comes out;
  * tfhub.dev needs to be updated with SavedModels created after said fix (which https://tfhub.dev/tensorflow/albert_en_base/2 is not).

**Comment by chenGitHuber** [comment] 2021-04-13 06:33
Hi @ziyuwwang and @cswhjiang 

We released the new albert tfhub model below. Could you please try again?

https://tfhub.dev/tensorflow/albert_en_large/3

**Comment by WGierke** [comment] 2021-06-03 09:53
I cannot reproduce the error anymore using https://tfhub.dev/tensorflow/albert_en_base/3 and TF 2.5.0:
```python
!pip install --quiet tensorflow==2.5.0
!pip install --quiet tensorflow-hub==0.12.0
!pip install --quiet tensorflow-text==2.5.0

import tensorflow_text
import tensorflow as tf
import tensorflow_hub as hub

text_input = tf.keras.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer("http://tfhub.dev/tensorflow/albert_en_preprocess/3")
encoder_inputs = preprocessor(text_input)
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/albert_en_base/3", trainable=True)
outputs = encoder(encoder_inputs)
sequence_output = outputs["sequence_output"]
output = tf.keras.layers.Dense(2)(sequence_output)
model = tf.keras.Model(inputs=text_input, outputs=output)
print(model.summary())

with tf.GradientTape(persistent=True) as tape:
    logits = model(tf.constant(["(your text here)"]))
    print(logits)
```
Please re-open the issue if I made a mistake while porting your code.

**Closed by WGierke** 2021-06-03 09:53 UTC
Labels: stat:awaiting response, subtype:text-embedding, type:bug
