### ISSUE TITLE
No gradient defined error on bert_multi_cased_L-12_H-768_A-12

### ISSUE THREAD

**Issue by hrk21** [tensorflow/hub#540] opened 2020-03-21 11:53 UTC
Setting trainable=True option while loading the model using hub.KerasLayers, triggers the error below while calling model.fit.

NotFoundError: [Derived]No gradient defined for op: StatefulPartitionedCall
[[{{node Func/_4}}]]
[[PartitionedCall/gradients/StatefulPartitionedCall_grad/PartitionedCall/gradients/StatefulPartitionedCall_grad/SymbolicGradient]] [Op:__inference_distributed_function_48070]

Function call stack:
distributed_function

**Comment by rmothukuru** [comment] 2020-03-23 06:24
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by hrk21** [comment] 2020-03-23 15:04
The model:
![image](https://user-images.githubusercontent.com/10379732/77325162-a494cc80-6d39-11ea-9aaf-1af93258e527.png)
Fit call:
![image](https://user-images.githubusercontent.com/10379732/77329936-7d8dc900-6d40-11ea-90e3-eb6f4716ca92.png)


Error from cell output:
![image](https://user-images.githubusercontent.com/10379732/77330661-7dda9400-6d41-11ea-81ea-64203786c1e6.png)

![image](https://user-images.githubusercontent.com/10379732/77330444-30f6bd80-6d41-11ea-9226-e6c024c42605.png)

![image](https://user-images.githubusercontent.com/10379732/77330529-4cfa5f00-6d41-11ea-9e70-79a78a92a338.png)

**Comment by TheGlobalist** [comment] 2020-03-23 15:27
This error is triggered regardless of the TF / TF-HUB Version

**Comment by arnoegw** [comment] 2020-03-24 10:18
Hi @hrk21, thank you for your report. I can reproduce the problem for TF 1.15.0 (with tf.enable_v2_behavior()) but I cannot reproduce the problem with TF 2.1.0 (which is currently the default on colab.research.google.com). Based on that, I am tentatively closing this issue.

If you have a complete, self-contained reproduction for TF2.1 or TF2.2rc including pip install commands in a notebook on https://colab.research.google.com or as a complete Python program (as text, not screenshot), please provide it and reopen this issue.

**Closed by arnoegw** 2020-03-24 10:18 UTC
Labels: stat:awaiting tensorflower, subtype:text-embedding, type:bug

**Comment by Husamx** [comment] 2020-03-25 20:30
@arnoegw  I get the same error when eager execuation is desabled with TF 2.1.0

**Comment by RobRomijnders** [comment] 2020-05-16 13:55
[I had a similar issue. Not sure if my solution applies. ]

I realized my hub module has several tags. Trying a more appropriate tag did have the gradient op.

Here's a code sample that you could quickly try:
For example, my module has tag '"A"' and tag '"B"'. For tag "B", the gradient op is defined, then the following should work:

```python
with tf.GradientTape() as tape:
  some_input = tf.random.uniform(shape=(13, 224, 224, 3))

  model = hub.KerasLayer("/path/to/hub", tags='B')

  some_output = model(some_input)
  loss = tf.reduce_mean((some_output)**2)

grad = tape.gradient(loss, im)
print(grad)
```

Running the same with tag '"A"' will fail with the same error.
