### ISSUE TITLE
hub.Keraslayer() compatibility issue with TPUs

### ISSUE THREAD

**Issue by orionpax00** [tensorflow/hub#613] opened 2020-06-12 06:27 UTC
Below code works fine on CPU and GPU but fails on TPU

```python
model = tf.keras.Sequential([
                hub.KerasLayer('https://tfhub.dev/tensorflow/efficientnet/b3/classification/1')
                tf.keras.layers.Dense(1, activation='sigmoid')
            ])

model.compile(
            optimizer=config.OPTIMIZER, 
            loss=config.LOSS, 
            metrics=config.ACCURACY
        )
history = model.fit(
        dataset, 
        epochs=config.EPOCHES, 
        steps_per_epoch=(config.TOTAL_TRAIN_IMG//config.BATCH_SIZE),
    )

```
![Imgur](https://i.imgur.com/Xxutgqi.png)

### versions
tensorflow: 2.2.0
tensorflow_hub: 0.8.0

**Comment by rmothukuru** [comment] 2020-06-12 11:28
@orionpax00,
While trying to reproduce your error, I have encountered an error, `NameError: name 'config' is not defined` . Can you please help us to reproduce your issue. Thanks!

**Comment by orionpax00** [comment] 2020-06-12 12:06
config is just a simple python class with designated values store in its variable 
**For Exampe**
```python
class config:
    OPTIMIZER: <value>
    ...
```

**Comment by gowthamkpr** [comment] 2020-06-12 16:37
@orionpax00 Can you update the reproducible code so we can reproduce it on colab. Thanks!

**Comment by rmothukuru** [comment] 2020-06-22 06:28
@orionpax00,
Can you please provide the complete code including Config File so that we can reproduce it and can look into it? Thanks!

**Comment by rmothukuru** [comment] 2020-06-29 12:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-06-29 12:09 UTC
Labels: hub, stat:awaiting response
