### ISSUE TITLE
Cannot download model

### ISSUE THREAD

**Issue by pawel12** [tensorflow/hub#56] opened 2018-05-23 07:23 UTC
Hello,

I'm not able to download any pre-trained mode. Neither from https://github.com/tensorflow/hub/blob/master/docs/modules/image.md nor using retrain.py script.
Is there some network issue?

**Comment by pawel12** [comment] 2018-05-29 07:20
Hi, 
Thank you for respond. I tried the command but it doesn't work. The problem is my network not tensor-flow hub because if I connect using connection from my phone it works.
This is a bit strange because I don't have any proxy or anything and this is the very first case I cannot download something...

**Comment by arnoegw** [comment] 2018-05-29 07:53
Thanks for your analysis. If it's not caused by TensorFlow Hub, and does not affect many users, please allow me to close this issue.

**Closed by arnoegw** 2018-05-29 07:53 UTC
